# encoding: utf8
from __future__ import unicode_literals

from ...symbols import ORTH, LEMMA, NORM, TAG


TOKENIZER_EXCEPTIONS = {
    "'slawer": [{'ORTH': "'slawer", 'LEMMA': "ys slawer", 'NORM': "ys slawer"}],
    'Arglwy': [{'ORTH': 'Arglwy', 'LEMMA': 'Arglwydd', 'NORM': 'Arglwydd'}],
    "Arglwy'": [{'ORTH': "Arglwy'", 'LEMMA': 'Arglwydd', 'NORM': 'Arglwydd'}],
    "Cymra'g": [{'ORTH': "Cymra'g", 'LEMMA': 'Cymraeg', 'NORM': 'Cymraeg'}],
    'Cymrag': [{'ORTH': 'Cymrag', 'LEMMA': 'Cymraeg', 'NORM': 'Cymraeg'}],
    'Cymrâg': [{'ORTH': 'Cymrâg', 'LEMMA': 'Cymraeg', 'NORM': 'Cymraeg'}],
    "Gymra'g": [{'ORTH': "Gymra'g", 'LEMMA': 'Cymraeg', 'NORM': 'Gymraeg'}],
    'Gymrag': [{'ORTH': 'Gymrag', 'LEMMA': 'Cymraeg', 'NORM': 'Gymraeg'}],
    'Gymrâg': [{'ORTH': 'Gymrâg', 'LEMMA': 'Cymraeg', 'NORM': 'Gymraeg'}],
    "'steddfod": [{'ORTH': "'steddfod", 'LEMMA': 'Eisteddfod', 'NORM': 'Eisteddfod'}],
    'steddfod': [{'ORTH': 'steddfod', 'LEMMA': 'Eisteddfod', 'NORM': 'Eisteddfod'}],
    "'Dolig": [{'ORTH': "'Dolig", 'LEMMA': 'Nadolig', 'NORM': 'Nadolig'}],
    "'dolig": [{'ORTH': "'dolig", 'LEMMA': 'Nadolig', 'NORM': 'Nadolig'}],
    'Dolig': [{'ORTH': 'Dolig', 'LEMMA': 'Nadolig', 'NORM': 'Nadolig'}],
    'dolig': [{'ORTH': 'dolig', 'LEMMA': 'Nadolig', 'NORM': 'Nadolig'}],
    'chlysur': [{'ORTH': 'chlysur', 'LEMMA': 'achlysur', 'NORM': 'achlysur'}],
    "'c'os": [{'ORTH': "'c'os", 'LEMMA': 'achos', 'NORM': 'achos'}],
    "'cos": [{'ORTH': "'cos", 'LEMMA': 'achos', 'NORM': 'achos'}],
    "c'os": [{'ORTH': "c'os", 'LEMMA': 'achos', 'NORM': 'achos'}],
    'chos': [{'ORTH': 'chos', 'LEMMA': 'achos', 'NORM': 'achos'}],
    'cos': [{'ORTH': 'cos', 'LEMMA': 'achos', 'NORM': 'achos'}],
    "'co": [{'ORTH': "'co", 'LEMMA': 'acw', 'NORM': 'acw'}],
    "'cw": [{'ORTH': "'cw", 'LEMMA': 'acw', 'NORM': 'acw'}],
    'co': [{'ORTH': 'co', 'LEMMA': 'acw', 'NORM': 'acw'}],
    'cw': [{'ORTH': 'cw', 'LEMMA': 'acw', 'NORM': 'acw'}],
    'gaddo': [{'ORTH': 'gaddo', 'LEMMA': 'addo', 'NORM': 'addo'}],
    'adag': [{'ORTH': 'adag', 'LEMMA': 'adeg', 'NORM': 'adeg'}],
    'adege': [{'ORTH': 'adege', 'LEMMA': 'adeg', 'NORM': 'adegau'}],
    "'nabod": [{'ORTH': "'nabod", 'LEMMA': 'adnabod', 'NORM': 'adnabod'}],
    'nabod': [{'ORTH': 'nabod', 'LEMMA': 'adnabod', 'NORM': 'adnabod'}],
    'adnode': [{'ORTH': 'adnode', 'LEMMA': 'adnod', 'NORM': 'adnodau'}],
    'adnodde': [{'ORTH': 'adnodde', 'LEMMA': 'adnodd', 'NORM': 'adnoddau'}],
    'aelode': [{'ORTH': 'aelode', 'LEMMA': 'aelod', 'NORM': 'aelodau'}],
    'gorad': [{'ORTH': 'gorad', 'LEMMA': 'agor', 'NORM': 'agored'}],
    "'gored": [{'ORTH': "'gored", 'LEMMA': 'agored', 'NORM': 'agored'}],
    'goriadau': [{'ORTH': 'goriadau', 'LEMMA': 'agoriad', 'NORM': 'agoriadau'}],
    'yfe': [{'ORTH': 'yfe', 'LEMMA': 'ai efe', 'NORM': 'ai efe'}],
    'amdana': [{'ORTH': 'amdana', 'LEMMA': 'am', 'NORM': 'amdanaf'}],
    "amdana'": [{'ORTH': "amdana'", 'LEMMA': 'am', 'NORM': 'amdanaf'}],
    'ama': [{'ORTH': 'ama', 'LEMMA': 'amau', 'NORM': 'amau'}],
    'ame': [{'ORTH': 'ame', 'LEMMA': 'amau', 'NORM': 'amau'}],
    'amball': [{'ORTH': 'amball', 'LEMMA': 'ambell', 'NORM': 'ambell'}],
    "'biti": [{'ORTH': "'biti", 'LEMMA': 'ambeutu', 'NORM': 'ambeutu'}],
    'ambiti': [{'ORTH': 'ambiti', 'LEMMA': 'ambeutu', 'NORM': 'ambeutu'}],
    'ambwyti': [{'ORTH': 'ambwyti', 'LEMMA': 'ambeutu', 'NORM': 'ambeutu'}],
    'ambyti': [{'ORTH': 'ambyti', 'LEMMA': 'ambeutu', 'NORM': 'ambeutu'}],
    'byti': [{'ORTH': 'byti', 'LEMMA': 'ambeutu', 'NORM': 'ambeutu'}],
    'amcangyfri': [{'ORTH': 'amcangyfri', 'LEMMA': 'amcangyfrif', 'NORM': 'amcangyfrif'}],
    'amal': [{'ORTH': 'amal', 'LEMMA': 'aml', 'NORM': 'aml'}],
    "'mrywiath": [{'ORTH': "'mrywiath", 'LEMMA': 'amrywiaeth', 'NORM': 'amrywiaeth'}],
    'amsar': [{'ORTH': 'amsar', 'LEMMA': 'amser', 'NORM': 'amser'}],
    'mynadd': [{'ORTH': 'mynadd', 'LEMMA': 'amynedd', 'NORM': 'amynedd'}],
    'mynedd': [{'ORTH': 'mynedd', 'LEMMA': 'amynedd', 'NORM': 'amynedd'}],
    'angan': [{'ORTH': 'angan', 'LEMMA': 'angen', 'NORM': 'angen'}],
    'anifeiliad': [{'ORTH': 'anifeiliad', 'LEMMA': 'anifaild', 'NORM': 'anifeiliaid'}],
    "annibyni'eth": [{'ORTH': "annibyni'eth", 'LEMMA': 'annibyniaeth', 'NORM': 'annibyniaeth'}],
    'annibynieth': [{'ORTH': 'annibynieth', 'LEMMA': 'annibyniaeth', 'NORM': 'annibyniaeth'}],
    'arwahan': [{'ORTH': 'arwahan', 'LEMMA': 'ar wahan', 'NORM': 'ar wahan'}],
    'ara': [{'ORTH': 'ara', 'LEMMA': 'araf', 'NORM': 'araf'}],
    'erill': [{'ORTH': 'erill', 'LEMMA': 'arall', 'NORM': 'eraill'}],
    'eryll': [{'ORTH': 'eryll', 'LEMMA': 'arall', 'NORM': 'eraill'}],
    'arfar': [{'ORTH': 'arfar', 'LEMMA': 'arfer', 'NORM': 'arfer'}],
    'arholiade': [{'ORTH': 'arholiade', 'LEMMA': 'arholiad', 'NORM': 'arholiadau'}],
    'arnach': [{'ORTH': 'arnach', 'LEMMA': 'arnach', 'NORM': 'arnoch'}],
    'atab': [{'ORTH': 'atab', 'LEMMA': 'ateb', 'NORM': 'ateb'}],
    'oria': [{'ORTH': 'oria', 'LEMMA': 'awr', 'NORM': 'oriau'}],
    'orie': [{'ORTH': 'orie', 'LEMMA': 'awr', 'NORM': 'oriau'}],
    'bech': [{'ORTH': 'bech', 'LEMMA': 'bach', 'NORM': 'bach'}],
    "'achan": [{'ORTH': "'achan", 'LEMMA': 'bachgen', 'NORM': 'fachgen'}],
    'achan': [{'ORTH': 'achan', 'LEMMA': 'bachgen', 'NORM': 'fachgen'}],
    'bandie': [{'ORTH': 'bandie', 'LEMMA': 'band', 'NORM': 'bandiau'}],
    'san': [{'ORTH': 'san', 'LEMMA': 'basai yn', 'NORM': 'basai yn'}],
    'be': [{'ORTH': 'be', 'LEMMA': 'beth', 'NORM': 'beth'}],
    "be'": [{'ORTH': "be'", 'LEMMA': 'beth', 'NORM': 'beth'}],
    'bedir': [{'ORTH': 'bedir', 'LEMMA': "beth ydy'r", 'NORM': "beth ydy'r"}],
    'fishi': [{'ORTH': 'fishi', 'LEMMA': 'bisi', 'NORM': 'fisi'}],
    'bloda': [{'ORTH': 'bloda', 'LEMMA': 'blodyn', 'NORM': 'blodau'}],
    'blode': [{'ORTH': 'blode', 'LEMMA': 'blodyn', 'NORM': 'blodau'}],
    'blynydde': [{'ORTH': 'blynydde', 'LEMMA': 'blwyddyn', 'NORM': 'blynyddoedd'}],
    "blynyddo'dd": [{'ORTH': "blynyddo'dd", 'LEMMA': 'blwyddyn', 'NORM': 'blynyddoedd'}],
    'blynyddodd': [{'ORTH': 'blynyddodd', 'LEMMA': 'blwyddyn', 'NORM': 'blynyddoedd'}],
    'flynadd': [{'ORTH': 'flynadd', 'LEMMA': 'blwyddyn', 'NORM': 'flynedd'}],
    'flynydde': [{'ORTH': 'flynydde', 'LEMMA': 'blwyddyn', 'NORM': 'flynyddoedd'}],
    "flynyddo'dd": [{'ORTH': "flynyddo'dd", 'LEMMA': 'blwyddyn', 'NORM': 'flynyddoedd'}],
    'flynyddodd': [{'ORTH': 'flynyddodd', 'LEMMA': 'blwyddyn', 'NORM': 'flynyddoedd'}],
    'mlynadd': [{'ORTH': 'mlynadd', 'LEMMA': 'blynedd', 'NORM': 'mlynedd'}],
    'basa': [{'ORTH': 'basa', 'LEMMA': 'bod', 'NORM': 'basai'}],
    'byse': [{'ORTH': 'byse', 'LEMMA': 'bod', 'NORM': 'basai'}],
    'byssa': [{'ORTH': 'byssa', 'LEMMA': 'bod', 'NORM': 'basai'}],
    'fase': [{'ORTH': 'fase', 'LEMMA': 'bod', 'NORM': 'basai'}],
    'fyse': [{'ORTH': 'fyse', 'LEMMA': 'bod', 'NORM': 'basai'}],
    "bo'": [{'ORTH': "bo'", 'LEMMA': 'bod', 'NORM': 'bod'}],
    'fasa': [{'ORTH': 'fasa', 'LEMMA': 'bod', 'NORM': 'buasai'}],
    "by'": [{'ORTH': "by'", 'LEMMA': 'bod', 'NORM': 'bydd'}],
    "bydde'": [{'ORTH': "bydde'", 'LEMMA': 'bod', 'NORM': 'bydd'}],
    'bydde': [{'ORTH': 'bydde', 'LEMMA': 'bod', 'NORM': 'byddai'}],
    "'sach": [{'ORTH': "'sach", 'LEMMA': 'bod', 'NORM': 'bysach'}],
    'fasat': [{'ORTH': 'fasat', 'LEMMA': 'bod', 'NORM': 'faset'}],
    'fuo': [{'ORTH': 'fuo', 'LEMMA': 'bod', 'NORM': 'fu'}],
    "fy'": [{'ORTH': "fy'", 'LEMMA': 'bod', 'NORM': 'fydd'}],
    "fydde'": [{'ORTH': "fydde'", 'LEMMA': 'bod', 'NORM': 'fydd'}],
    'fydda': [{'ORTH': 'fydda', 'LEMMA': 'bod', 'NORM': 'fyddaf'}],
    "fydda'": [{'ORTH': "fydda'", 'LEMMA': 'bod', 'NORM': 'fyddaf'}],
    'fydde': [{'ORTH': 'fydde', 'LEMMA': 'bod', 'NORM': 'fyddai'}],
    "ma'": [{'ORTH': "ma'", 'LEMMA': 'bod', 'NORM': 'mae'}],
    'dd': [{'ORTH': 'dd', 'LEMMA': 'bod', 'NORM': 'oedd'}],
    "o'dd": [{'ORTH': "o'dd", 'LEMMA': 'bod', 'NORM': 'oedd'}],
    "o'dda": [{'ORTH': "o'dda", 'LEMMA': 'bod', 'NORM': 'oedd'}],
    'odd': [{'ORTH': 'odd', 'LEMMA': 'bod', 'NORM': 'oedd'}],
    'oe': [{'ORTH': 'oe', 'LEMMA': 'bod', 'NORM': 'oedd'}],
    "oe'": [{'ORTH': "oe'", 'LEMMA': 'bod', 'NORM': 'oedd'}],
    "'dech": [{'ORTH': "'dech", 'LEMMA': 'bod', 'NORM': 'oeddech'}],
    "o'ddach": [{'ORTH': "o'ddach", 'LEMMA': 'bod', 'NORM': 'oeddech'}],
    'oddach': [{'ORTH': 'oddach', 'LEMMA': 'bod', 'NORM': 'oeddech'}],
    "'den": [{'ORTH': "'den", 'LEMMA': 'bod', 'NORM': 'oedden'}],
    "o'ddan": [{'ORTH': "o'ddan", 'LEMMA': 'bod', 'NORM': 'oedden'}],
    "o'dden": [{'ORTH': "o'dden", 'LEMMA': 'bod', 'NORM': 'oedden'}],
    'oddan': [{'ORTH': 'oddan', 'LEMMA': 'bod', 'NORM': 'oedden'}],
    'odden': [{'ORTH': 'odden', 'LEMMA': 'bod', 'NORM': 'oedden'}],
    "o't": [{'ORTH': "o't", 'LEMMA': 'bod', 'NORM': 'oeddet'}],
    'oeddat': [{'ORTH': 'oeddat', 'LEMMA': 'bod', 'NORM': 'oeddit'}],
    "o's": [{'ORTH': "o's", 'LEMMA': 'bod', 'NORM': 'oes'}],
    "r'oedd": [{'ORTH': "r'oedd", 'LEMMA': 'bod', 'NORM': 'roedd'}],
    "ro'dd": [{'ORTH': "ro'dd", 'LEMMA': 'bod', 'NORM': 'roedd'}],
    'roedd': [{'ORTH': 'roedd', 'LEMMA': 'bod', 'NORM': 'roedd'}],
    "r'on": [{'ORTH': "r'on", 'LEMMA': 'bod', 'NORM': 'roeddwn'}],
    "'wy": [{'ORTH': "'wy", 'LEMMA': 'bod', 'NORM': 'rwy'}],
    "'yf": [{'ORTH': "'yf", 'LEMMA': 'bod', 'NORM': 'rwyf'}],
    'rydach': [{'ORTH': 'rydach', 'LEMMA': 'bod', 'NORM': 'rydych'}],
    "s'": [{'ORTH': "s'", 'LEMMA': 'bod', 'NORM': 'sydd'}],
    'sy': [{'ORTH': 'sy', 'LEMMA': 'bod', 'NORM': 'sydd'}],
    "sy'": [{'ORTH': "sy'", 'LEMMA': 'bod', 'NORM': 'sydd'}],
    "wy'": [{'ORTH': "wy'", 'LEMMA': 'bod', 'NORM': 'wyf'}],
    "w't": [{'ORTH': "w't", 'LEMMA': 'bod', 'NORM': 'wyt'}],
    'yt': [{'ORTH': 'yt', 'LEMMA': 'bod', 'NORM': 'wyt'}],
    'odw': [{'ORTH': 'odw', 'LEMMA': 'bod', 'NORM': 'ydw'}],
    'yndw': [{'ORTH': 'yndw', 'LEMMA': 'bod', 'NORM': 'ydw'}],
    'ody': [{'ORTH': 'ody', 'LEMMA': 'bod', 'NORM': 'ydy'}],
    'yndi': [{'ORTH': 'yndi', 'LEMMA': 'bod', 'NORM': 'ydy'}],
    'dach': [{'ORTH': 'dach', 'LEMMA': 'bod', 'NORM': 'ydych'}],
    'dych': [{'ORTH': 'dych', 'LEMMA': 'bod', 'NORM': 'ydych'}],
    'ydach': [{'ORTH': 'ydach', 'LEMMA': 'bod', 'NORM': 'ydych'}],
    'ydech': [{'ORTH': 'ydech', 'LEMMA': 'bod', 'NORM': 'ydych'}],
    'ydan': [{'ORTH': 'ydan', 'LEMMA': 'bod', 'NORM': 'ydym'}],
    "y'": [{'ORTH': "y'", 'LEMMA': 'bod', 'NORM': 'ydyn'}],
    'yden': [{'ORTH': 'yden', 'LEMMA': 'bod', 'NORM': 'ydyn'}],
    'yndan': [{'ORTH': 'yndan', 'LEMMA': 'bod', 'NORM': 'ydyn'}],
    'yndyn': [{'ORTH': 'yndyn', 'LEMMA': 'bod', 'NORM': 'ydyn'}],
    'yndyw': [{'ORTH': 'yndyw', 'LEMMA': 'bod', 'NORM': 'ydyw'}],
    'busnas': [{'ORTH': 'busnas', 'LEMMA': 'busnes', 'NORM': 'busnes'}],
    'busnese': [{'ORTH': 'busnese', 'LEMMA': 'busnes', 'NORM': 'busnesau'}],
    'bwco': [{'ORTH': 'bwco', 'LEMMA': 'bwcio', 'NORM': 'bwcio'}],
    'bwr': [{'ORTH': 'bwr', 'LEMMA': 'bwrdd', 'NORM': 'bwrdd'}],
    "b'yta": [{'ORTH': "b'yta", 'LEMMA': 'bwyta', 'NORM': 'bwyta'}],
    'bita': [{'ORTH': 'bita', 'LEMMA': 'bwyta', 'NORM': 'bwyta'}],
    'byta': [{'ORTH': 'byta', 'LEMMA': 'bwyta', 'NORM': 'bwyta'}],
    "f'yta": [{'ORTH': "f'yta", 'LEMMA': 'bwyta', 'NORM': 'bwyta'}],
    'fyta': [{'ORTH': 'fyta', 'LEMMA': 'bwyta', 'NORM': 'bwyta'}],
    'ychan': [{'ORTH': 'ychan', 'LEMMA': 'bychan', 'NORM': 'bychan'}],
    'bywyda': [{'ORTH': 'bywyda', 'LEMMA': 'bywyd', 'NORM': 'bywydau'}],
    'bywyde': [{'ORTH': 'bywyde', 'LEMMA': 'bywyd', 'NORM': 'bywydau'}],
    "c'mon": [{'ORTH': "c'mon", 'LEMMA': "c'mon", 'NORM': "c'mon"}],
    'cacan': [{'ORTH': 'cacan', 'LEMMA': 'cacen', 'NORM': 'cacen'}],
    "ca'l": [{'ORTH': "ca'l", 'LEMMA': 'cael', 'NORM': 'cael'}],
    'cel': [{'ORTH': 'cel', 'LEMMA': 'cael', 'NORM': 'cael'}],
    "c'ath": [{'ORTH': "c'ath", 'LEMMA': 'cael', 'NORM': 'cafodd'}],
    'gaethoch': [{'ORTH': 'gaethoch', 'LEMMA': 'cael', 'NORM': 'cawsoch'}],
    "cha'l": [{'ORTH': "cha'l", 'LEMMA': 'cael', 'NORM': 'chael'}],
    "ga'l": [{'ORTH': "ga'l", 'LEMMA': 'cael', 'NORM': 'gael'}],
    "ga'th": [{'ORTH': "ga'th", 'LEMMA': 'cael', 'NORM': 'gafodd'}],
    'gewn': [{'ORTH': 'gewn', 'LEMMA': 'cael', 'NORM': 'gawn'}],
    'gesh': [{'ORTH': 'gesh', 'LEMMA': 'cael', 'NORM': 'ges'}],
    'galad': [{'ORTH': 'galad', 'LEMMA': 'caled', 'NORM': 'galed'}],
    'calonne': [{'ORTH': 'calonne', 'LEMMA': 'calon', 'NORM': 'calonnau'}],
    'ganiata': [{'ORTH': 'ganiata', 'LEMMA': 'caniatau', 'NORM': 'ganiatau'}],
    'cardia': [{'ORTH': 'cardia', 'LEMMA': 'carden', 'NORM': 'cardiau'}],
    "ca'tre'": [{'ORTH': "ca'tre'", 'LEMMA': 'cartref', 'NORM': 'cartref'}],
    'cartra': [{'ORTH': 'cartra', 'LEMMA': 'cartref', 'NORM': 'cartref'}],
    'cartre': [{'ORTH': 'cartre', 'LEMMA': 'cartref', 'NORM': 'cartref'}],
    'catre': [{'ORTH': 'catre', 'LEMMA': 'cartref', 'NORM': 'cartref'}],
    'gytre': [{'ORTH': 'gytre', 'LEMMA': 'cartref', 'NORM': 'gartref'}],
    'ceffyle': [{'ORTH': 'ceffyle', 'LEMMA': 'ceffyl', 'NORM': 'ceffylau'}],
    'cefen': [{'ORTH': 'cefen', 'LEMMA': 'cefn', 'NORM': 'cefn'}],
    'gefen': [{'ORTH': 'gefen', 'LEMMA': 'cefn', 'NORM': 'gefn'}],
    'cerddad': [{'ORTH': 'cerddad', 'LEMMA': 'cerdded', 'NORM': 'cerdded'}],
    'gerddad': [{'ORTH': 'gerddad', 'LEMMA': 'cerdded', 'NORM': 'gerdded'}],
    "cerddori'eth": [{'ORTH': "cerddori'eth", 'LEMMA': 'cerddoriaeth', 'NORM': 'cerddoriaeth'}],
    'cerddorieth': [{'ORTH': 'cerddorieth', 'LEMMA': 'cerddoriaeth', 'NORM': 'cerddoriaeth'}],
    "gerddori'eth": [{'ORTH': "gerddori'eth", 'LEMMA': 'cerddoriaeth', 'NORM': 'gerddoriaeth'}],
    'gerddorieth': [{'ORTH': 'gerddorieth', 'LEMMA': 'cerddoriaeth', 'NORM': 'gerddoriaeth'}],
    "ch'wel": [{'ORTH': "ch'wel", 'LEMMA': "ch'n gweld", 'NORM': "chi'n gweld"}],
    'chitha': [{'ORTH': 'chitha', 'LEMMA': 'chi', 'NORM': 'chithau'}],
    "chi'so": [{'ORTH': "chi'so", 'LEMMA': 'chi eisiau', 'NORM': 'chi eisiau'}],
    'chiso': [{'ORTH': 'chiso', 'LEMMA': 'chi eisiau', 'NORM': 'chi eisiau'}],
    'chwel': [{'ORTH': 'chwel', 'LEMMA': "chi'n gweld", 'NORM': "chi'n gweld"}],
    "ch'mo": [{'ORTH': "ch'mo", 'LEMMA': "chi'n gwybod", 'NORM': "chi'n gwybod"}],
    "ch'mod": [{'ORTH': "ch'mod", 'LEMMA': "chi'n gwybod", 'NORM': "chi'n gwybod"}],
    "chi'mod": [{'ORTH': "chi'mod", 'LEMMA': "chi'n gwybod", 'NORM': "chi'n gwybod"}],
    "'hwarae": [{'ORTH': "'hwarae", 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    "'whar'e": [{'ORTH': "'whar'e", 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    "chwar'e": [{'ORTH': "chwar'e", 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    'chwara': [{'ORTH': 'chwara', 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    'chware': [{'ORTH': 'chware', 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    'hwarae': [{'ORTH': 'hwarae', 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    'ware': [{'ORTH': 'ware', 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    'whare': [{'ORTH': 'whare', 'LEMMA': 'chwarae', 'NORM': 'chwarae'}],
    "'wech": [{'ORTH': "'wech", 'LEMMA': 'chwech', 'NORM': 'chwech'}],
    'wech': [{'ORTH': 'wech', 'LEMMA': 'chwech', 'NORM': 'chwech'}],
    "'werthin": [{'ORTH': "'werthin", 'LEMMA': 'chwerthin', 'NORM': 'chwerthin'}],
    'werthin': [{'ORTH': 'werthin', 'LEMMA': 'chwerthin', 'NORM': 'chwerthin'}],
    'cino': [{'ORTH': 'cino', 'LEMMA': 'cinio', 'NORM': 'cinio'}],
    'clybie': [{'ORTH': 'clybie', 'LEMMA': 'clwb', 'NORM': 'clybiau'}],
    "cl'wad": [{'ORTH': "cl'wad", 'LEMMA': 'clywed', 'NORM': 'clywed'}],
    "cl'wed": [{'ORTH': "cl'wed", 'LEMMA': 'clywed', 'NORM': 'clywed'}],
    'clwad': [{'ORTH': 'clwad', 'LEMMA': 'clywed', 'NORM': 'clywed'}],
    'clwed': [{'ORTH': 'clwed', 'LEMMA': 'clywed', 'NORM': 'clywed'}],
    'clywad': [{'ORTH': 'clywad', 'LEMMA': 'clywed', 'NORM': 'clywed'}],
    "gl'wad": [{'ORTH': "gl'wad", 'LEMMA': 'clywed', 'NORM': 'glywed'}],
    'glwad': [{'ORTH': 'glwad', 'LEMMA': 'clywed', 'NORM': 'glywed'}],
    'glywad': [{'ORTH': 'glywad', 'LEMMA': 'clywed', 'NORM': 'glywed'}],
    'cre': [{'ORTH': 'cre', 'LEMMA': 'credu', 'NORM': 'credu'}],
    'gry': [{'ORTH': 'gry', 'LEMMA': 'cryf', 'NORM': 'gryf'}],
    'gula': [{'ORTH': 'gula', 'LEMMA': 'cul', 'NORM': 'gulaf'}],
    "gula'": [{'ORTH': "gula'", 'LEMMA': 'cul', 'NORM': 'gulaf'}],
    'chwartar': [{'ORTH': 'chwartar', 'LEMMA': 'cwarter', 'NORM': 'chwarter'}],
    'cwestiynne': [{'ORTH': 'cwestiynne', 'LEMMA': 'cwestiwn', 'NORM': 'cwestiynnau'}],
    'gwestiyne': [{'ORTH': 'gwestiyne', 'LEMMA': 'cwestiwn', 'NORM': 'gwestiynau'}],
    'cwestiyne': [{'ORTH': 'cwestiyne', 'LEMMA': 'cwestwn', 'NORM': 'cwestiynau'}],
    'cyrsie': [{'ORTH': 'cyrsie', 'LEMMA': 'cwrs', 'NORM': 'cyrsiau'}],
    'cyrsia': [{'ORTH': 'cyrsia', 'LEMMA': 'cwrsa', 'NORM': 'cyrsiau'}],
    "cw'mpo": [{'ORTH': "cw'mpo", 'LEMMA': 'cwympo', 'NORM': 'cwmpo'}],
    'cwmpo': [{'ORTH': 'cwmpo', 'LEMMA': 'cwympo', 'NORM': 'cwmpo'}],
    'cyfadde': [{'ORTH': 'cyfadde', 'LEMMA': 'cyfaddef', 'NORM': 'cyfaddef'}],
    'gyfadde': [{'ORTH': 'gyfadde', 'LEMMA': 'cyfaddef', 'NORM': 'gyfaddef'}],
    'cyfa': [{'ORTH': 'cyfa', 'LEMMA': 'cyfan', 'NORM': 'cyfan'}],
    'gyfar': [{'ORTH': 'gyfar', 'LEMMA': 'cyfer', 'NORM': 'gyfer'}],
    'cyfla': [{'ORTH': 'cyfla', 'LEMMA': 'cyfle', 'NORM': 'cyfle'}],
    'cyfrynge': [{'ORTH': 'cyfrynge', 'LEMMA': 'cyfrwng', 'NORM': 'cyfryngau'}],
    'cyment': [{'ORTH': 'cyment', 'LEMMA': 'cymaint', 'NORM': 'cymaint'}],
    "gym'int": [{'ORTH': "gym'int", 'LEMMA': 'cymaint', 'NORM': 'cymaint'}],
    'gymint': [{'ORTH': 'gymint', 'LEMMA': 'cymaint', 'NORM': 'cymaint'}],
    'gyment': [{'ORTH': 'gyment', 'LEMMA': 'cymaint', 'NORM': 'gymaint'}],
    "cym'ryd": [{'ORTH': "cym'ryd", 'LEMMA': 'cymryd', 'NORM': 'cymryd'}],
    "cym'yd": [{'ORTH': "cym'yd", 'LEMMA': 'cymryd', 'NORM': 'cymryd'}],
    'cymyd': [{'ORTH': 'cymyd', 'LEMMA': 'cymryd', 'NORM': 'cymryd'}],
    "gym'yd": [{'ORTH': "gym'yd", 'LEMMA': 'cymryd', 'NORM': 'gymryd'}],
    'gymeryd': [{'ORTH': 'gymeryd', 'LEMMA': 'cymryd', 'NORM': 'gymryd'}],
    'gymyd': [{'ORTH': 'gymyd', 'LEMMA': 'cymryd', 'NORM': 'gymryd'}],
    'cymuneda': [{'ORTH': 'cymuneda', 'LEMMA': 'cymuned', 'NORM': 'cymunedau'}],
    'cymunede': [{'ORTH': 'cymunede', 'LEMMA': 'cymuned', 'NORM': 'cymunedau'}],
    'cynllunie': [{'ORTH': 'cynllunie', 'LEMMA': 'cynllun', 'NORM': 'cynlluniau'}],
    'cynta': [{'ORTH': 'cynta', 'LEMMA': 'cyntaf', 'NORM': 'cyntaf'}],
    "cynta'": [{'ORTH': "cynta'", 'LEMMA': 'cyntaf', 'NORM': 'cyntaf'}],
    'gynta': [{'ORTH': 'gynta', 'LEMMA': 'cyntaf', 'NORM': 'gyntaf'}],
    "gynta'": [{'ORTH': "gynta'", 'LEMMA': 'cyntaf', 'NORM': 'gyntaf'}],
    "cyrr'edd": [{'ORTH': "cyrr'edd", 'LEMMA': 'cyrraedd', 'NORM': 'cyrraedd'}],
    "cyrra'dd": [{'ORTH': "cyrra'dd", 'LEMMA': 'cyrraedd', 'NORM': 'cyrraedd'}],
    'cyrradd': [{'ORTH': 'cyrradd', 'LEMMA': 'cyrraedd', 'NORM': 'cyrraedd'}],
    'cyrredd': [{'ORTH': 'cyrredd', 'LEMMA': 'cyrraedd', 'NORM': 'cyrraedd'}],
    "gyrra'dd": [{'ORTH': "gyrra'dd", 'LEMMA': 'cyrraedd', 'NORM': 'gyrraedd'}],
    'gyrradd': [{'ORTH': 'gyrradd', 'LEMMA': 'cyrraedd', 'NORM': 'gyrraedd'}],
    'sidro': [{'ORTH': 'sidro', 'LEMMA': 'cysidro', 'NORM': 'cysidro'}],
    'dachre': [{'ORTH': 'dachre', 'LEMMA': 'dachrau', 'NORM': 'dachrau'}],
    'dadla': [{'ORTH': 'dadla', 'LEMMA': 'dadlau', 'NORM': 'dadlau'}],
    "dadla'": [{'ORTH': "dadla'", 'LEMMA': 'dadlau', 'NORM': 'dadlau'}],
    'ddadla': [{'ORTH': 'ddadla', 'LEMMA': 'dadlau', 'NORM': 'ddadlau'}],
    "ddadla'": [{'ORTH': "ddadla'", 'LEMMA': 'dadlau', 'NORM': 'ddadlau'}],
    'defed': [{'ORTH': 'defed', 'LEMMA': 'dafad', 'NORM': 'defaid'}],
    'darllan': [{'ORTH': 'darllan', 'LEMMA': 'darllen', 'NORM': 'darllen'}],
    'darne': [{'ORTH': 'darne', 'LEMMA': 'darn', 'NORM': 'darnau'}],
    'aru': [{'ORTH': 'aru', 'LEMMA': 'daru', 'NORM': 'daru'}],
    'ddarllan': [{'ORTH': 'ddarllan', 'LEMMA': 'ddarllen', 'NORM': 'ddarllen'}],
    'ddigwyddiade': [{'ORTH': 'ddigwyddiade', 'LEMMA': 'ddigwyddiad', 'NORM': 'ddigwyddiadau'}],
    'ddyddia': [{'ORTH': 'ddyddia', 'LEMMA': 'ddydd', 'NORM': 'ddyddiau'}],
    "d'allt": [{'ORTH': "d'allt", 'LEMMA': 'deall', 'NORM': 'deall'}],
    'ddechra': [{'ORTH': 'ddechra', 'LEMMA': 'dechrau', 'NORM': 'ddechrau'}],
    "ddechra'": [{'ORTH': "ddechra'", 'LEMMA': 'dechrau', 'NORM': 'ddechrau'}],
    'ddechre': [{'ORTH': 'ddechre', 'LEMMA': 'dechrau', 'NORM': 'ddechrau'}],
    'dechra': [{'ORTH': 'dechra', 'LEMMA': 'dechrau', 'NORM': 'dechrau'}],
    "dechra'": [{'ORTH': "dechra'", 'LEMMA': 'dechrau', 'NORM': 'dechrau'}],
    'dechre': [{'ORTH': 'dechre', 'LEMMA': 'dechrau', 'NORM': 'dechrau'}],
    'dege': [{'ORTH': 'dege', 'LEMMA': 'deg', 'NORM': 'degau'}],
    'dierth': [{'ORTH': 'dierth', 'LEMMA': 'dieithr', 'NORM': 'dieithr'}],
    'digwyddiade': [{'ORTH': 'digwyddiade', 'LEMMA': 'digwyddiad', 'NORM': 'digwyddiadau'}],
    "'im": [{'ORTH': "'im", 'LEMMA': 'dim', 'NORM': 'dim'}],
    'im': [{'ORTH': 'im', 'LEMMA': 'dim', 'NORM': 'dim'}],
    "'mond": [{'ORTH': "'mond", 'LEMMA': 'dim ond', 'NORM': 'dim ond'}],
    "m'ond": [{'ORTH': "m'ond", 'LEMMA': 'dim ond', 'NORM': 'dim ond'}],
    'mond': [{'ORTH': 'mond', 'LEMMA': 'dim ond', 'NORM': 'dim ond'}],
    'nunlla': [{'ORTH': 'nunlla', 'LEMMA': 'dim un lle', 'NORM': 'dim un lle'}],
    'nunlle': [{'ORTH': 'nunlle', 'LEMMA': 'dim un lle', 'NORM': 'dim un lle'}],
    'diodde': [{'ORTH': 'diodde', 'LEMMA': 'dioddef', 'NORM': 'dioddef'}],
    "disgw'l": [{'ORTH': "disgw'l", 'LEMMA': 'disgwyl', 'NORM': 'disgwyl'}],
    'disgwl': [{'ORTH': 'disgwl', 'LEMMA': 'disgwyl', 'NORM': 'disgwyl'}],
    "dishgw'l": [{'ORTH': "dishgw'l", 'LEMMA': 'disgwyl', 'NORM': 'disgwyl'}],
    'dishgwl': [{'ORTH': 'dishgwl', 'LEMMA': 'disgwyl', 'NORM': 'disgwyl'}],
    'diwadd': [{'ORTH': 'diwadd', 'LEMMA': 'diwedd', 'NORM': 'diwedd'}],
    "dd'wetha": [{'ORTH': "dd'wetha", 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    "dd'wetha'": [{'ORTH': "dd'wetha'", 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    "dd'wytha'": [{'ORTH': "dd'wytha'", 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    'ddiwetha': [{'ORTH': 'ddiwetha', 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    "ddiwetha'": [{'ORTH': "ddiwetha'", 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    'ddwetha': [{'ORTH': 'ddwetha', 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    "ddwetha'": [{'ORTH': "ddwetha'", 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    'ddwytha': [{'ORTH': 'ddwytha', 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    "ddwytha'": [{'ORTH': "ddwytha'", 'LEMMA': 'diwethaf', 'NORM': 'ddiwethaf'}],
    "d'wetha": [{'ORTH': "d'wetha", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "d'wetha'": [{'ORTH': "d'wetha'", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "d'wethaf": [{'ORTH': "d'wethaf", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "d'wytha": [{'ORTH': "d'wytha", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "d'wytha'": [{'ORTH': "d'wytha'", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    'diwetha': [{'ORTH': 'diwetha', 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "diwetha'": [{'ORTH': "diwetha'", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    'dwetha': [{'ORTH': 'dwetha', 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "dwetha'": [{'ORTH': "dwetha'", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    'dwethaf': [{'ORTH': 'dwethaf', 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    'dwytha': [{'ORTH': 'dwytha', 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "dwytha'": [{'ORTH': "dwytha'", 'LEMMA': 'diwethaf', 'NORM': 'diwethaf'}],
    "dd'wrnod": [{'ORTH': "dd'wrnod", 'LEMMA': 'diwrnod', 'NORM': 'ddiwrnod'}],
    'ddwrnod': [{'ORTH': 'ddwrnod', 'LEMMA': 'diwrnod', 'NORM': 'ddiwrnod'}],
    "d'wrnod": [{'ORTH': "d'wrnod", 'LEMMA': 'diwrnod', 'NORM': 'diwrnod'}],
    'dwrnod': [{'ORTH': 'dwrnod', 'LEMMA': 'diwrnod', 'NORM': 'diwrnod'}],
    'diwrnode': [{'ORTH': 'diwrnode', 'LEMMA': 'diwrnod', 'NORM': 'diwrnodau'}],
    'ddath': [{'ORTH': 'ddath', 'LEMMA': 'dod', 'NORM': 'ddaeth'}],
    'ddoth': [{'ORTH': 'ddoth', 'LEMMA': 'dod', 'NORM': 'ddaeth'}],
    'ddois': [{'ORTH': 'ddois', 'LEMMA': 'dod', 'NORM': 'ddoi'}],
    'der': [{'ORTH': 'der', 'LEMMA': 'dod', 'NORM': 'dere'}],
    'dwad': [{'ORTH': 'dwad', 'LEMMA': 'dod', 'NORM': 'dod'}],
    'tud': [{'ORTH': 'tud', 'LEMMA': 'dod', 'NORM': 'tyrd'}],
    'tyd': [{'ORTH': 'tyd', 'LEMMA': 'dod', 'NORM': 'tyrd'}],
    "do'dd": [{'ORTH': "do'dd", 'LEMMA': 'doedd', 'NORM': 'doedd'}],
    "'sdim": [{'ORTH': "'sdim", 'LEMMA': 'does dim', 'NORM': 'does dim'}],
    "s'dim": [{'ORTH': "s'dim", 'LEMMA': 'does dim', 'NORM': 'does dim'}],
    "s'im": [{'ORTH': "s'im", 'LEMMA': 'does dim', 'NORM': 'does dim'}],
    'sdim': [{'ORTH': 'sdim', 'LEMMA': 'does dim', 'NORM': 'does dim'}],
    "s'neb": [{'ORTH': "s'neb", 'LEMMA': 'does neb', 'NORM': 'does neb'}],
    'sneb': [{'ORTH': 'sneb', 'LEMMA': 'does neb', 'NORM': 'does neb'}],
    'snam': [{'ORTH': 'snam', 'LEMMA': 'does yna ddim', 'NORM': 'does yna ddim'}],
    'sym': [{'ORTH': 'sym', 'LEMMA': 'does yna ddim', 'NORM': 'does yna ddim'}],
    'dosbarthiade': [{'ORTH': 'dosbarthiade', 'LEMMA': 'dosbarth', 'NORM': 'dosbarthiadau'}],
    "drafod'eth": [{'ORTH': "drafod'eth", 'LEMMA': 'drafodaeth', 'NORM': 'drafodaeth'}],
    'drafodeth': [{'ORTH': 'drafodeth', 'LEMMA': 'drafodaeth', 'NORM': 'drafodaeth'}],
    'drost': [{'ORTH': 'drost', 'LEMMA': 'dros', 'NORM': 'dros'}],
    "dd'eu": [{'ORTH': "dd'eu", 'LEMMA': 'dweud', 'NORM': 'ddweud'}],
    "dd'eu'": [{'ORTH': "dd'eu'", 'LEMMA': 'dweud', 'NORM': 'ddweud'}],
    "dd'eud": [{'ORTH': "dd'eud", 'LEMMA': 'dweud', 'NORM': 'ddweud'}],
    'ddeud': [{'ORTH': 'ddeud', 'LEMMA': 'dweud', 'NORM': 'ddweud'}],
    'wedes': [{'ORTH': 'wedes', 'LEMMA': 'dweud', 'NORM': 'ddywedais'}],
    'ddudodd': [{'ORTH': 'ddudodd', 'LEMMA': 'dweud', 'NORM': 'ddywedodd'}],
    "'dwch": [{'ORTH': "'dwch", 'LEMMA': 'dweud', 'NORM': 'dwedwch'}],
    'dwch': [{'ORTH': 'dwch', 'LEMMA': 'dweud', 'NORM': 'dwedwch'}],
    "d'eu": [{'ORTH': "d'eu", 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    "d'eu'": [{'ORTH': "d'eu'", 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    "d'eud": [{'ORTH': "d'eud", 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    'deud': [{'ORTH': 'deud', 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    'dwe': [{'ORTH': 'dwe', 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    'dwed': [{'ORTH': 'dwed', 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    'dweu': [{'ORTH': 'dweu', 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    'gwed': [{'ORTH': 'gwed', 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    'weud': [{'ORTH': 'weud', 'LEMMA': 'dweud', 'NORM': 'dweud'}],
    "d'wad": [{'ORTH': "d'wad", 'LEMMA': 'dweud', 'NORM': 'dywed'}],
    'duda': [{'ORTH': 'duda', 'LEMMA': 'dweud', 'NORM': 'dyweda'}],
    'dwedes': [{'ORTH': 'dwedes', 'LEMMA': 'dweud', 'NORM': 'dywedais'}],
    'wedest': [{'ORTH': 'wedest', 'LEMMA': 'dweud', 'NORM': 'dywedaist'}],
    'wedoch': [{'ORTH': 'wedoch', 'LEMMA': 'dweud', 'NORM': 'dywedoch'}],
    "me'": [{'ORTH': "me'", 'LEMMA': 'dweud', 'NORM': 'meddai'}],
    "deu'tha": [{'ORTH': "deu'tha", 'LEMMA': 'dweud wrth', 'NORM': 'dweud wrth'}],
    'deutha': [{'ORTH': 'deutha', 'LEMMA': 'dweud wrth', 'NORM': 'dweud wrth'}],
    'wbo': [{'ORTH': 'wbo', 'LEMMA': 'dwi ddim yn gwybod', 'NORM': 'dwi ddim yn gwybod'}],
    'ddy': [{'ORTH': 'ddy', 'LEMMA': 'dydd', 'NORM': 'ddydd'}],
    "ddy'": [{'ORTH': "ddy'", 'LEMMA': 'dydd', 'NORM': 'ddydd'}],
    'ddyddie': [{'ORTH': 'ddyddie', 'LEMMA': 'dydd', 'NORM': 'ddyddiau'}],
    "dy'": [{'ORTH': "dy'", 'LEMMA': 'dydd', 'NORM': 'dydd'}],
    'dyddia': [{'ORTH': 'dyddia', 'LEMMA': 'dydd', 'NORM': 'dyddiau'}],
    'dyddie': [{'ORTH': 'dyddie', 'LEMMA': 'dydd', 'NORM': 'dyddiau'}],
    'dwim': [{'ORTH': 'dwim', 'LEMMA': 'dydw i ddim', 'NORM': 'dydw i ddim'}],
    'soi': [{'ORTH': 'soi', 'LEMMA': 'dydw i ddim', 'NORM': 'dydw i ddim'}],
    'dwmbo': [{'ORTH': 'dwmbo', 'LEMMA': 'dydw i ddim yn gwybod', 'NORM': 'dydw i ddim yn gwybod'}],
    'ddyle': [{'ORTH': 'ddyle', 'LEMMA': 'dylu', 'NORM': 'dylai'}],
    'dylsa': [{'ORTH': 'dylsa', 'LEMMA': 'dylu', 'NORM': 'dylasai'}],
    "n'efe": [{'ORTH': "n'efe", 'LEMMA': 'dyna efe', 'NORM': 'dyna efe'}],
    'ddynas': [{'ORTH': 'ddynas', 'LEMMA': 'dynes', 'NORM': 'ddynes'}],
    'dynas': [{'ORTH': 'dynas', 'LEMMA': 'dynes', 'NORM': 'dynes'}],
    'deuth': [{'ORTH': 'deuth', 'LEMMA': 'dyweda wrth', 'NORM': 'dyweda wrth'}],
    'wedodd': [{'ORTH': 'wedodd', 'LEMMA': 'dywedodd', 'NORM': 'dywedodd'}],
    'ddywedyd': [{'ORTH': 'ddywedyd', 'LEMMA': 'dywedyd', 'NORM': 'dweud'}],
    'dywedyd': [{'ORTH': 'dywedyd', 'LEMMA': 'dywedyd', 'NORM': 'dweud'}],
    'edrach': [{'ORTH': 'edrach', 'LEMMA': 'edrych', 'NORM': 'edrych'}],
    "'drychwch": [{'ORTH': "'drychwch", 'LEMMA': 'edrych', 'NORM': 'edrychwch'}],
    'drychwch': [{'ORTH': 'drychwch', 'LEMMA': 'edrych', 'NORM': 'edrychwch'}],
    "'lwch": [{'ORTH': "'lwch", 'LEMMA': 'edrych', 'NORM': 'ylwch'}],
    'e': [{'ORTH': 'e', 'LEMMA': 'ef', 'NORM': 'ef'}],
    "e'": [{'ORTH': "e'", 'LEMMA': 'ef', 'NORM': 'ef'}],
    "'falla": [{'ORTH': "'falla", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "'fallai": [{'ORTH': "'fallai", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "'falle": [{'ORTH': "'falle", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "e'lla": [{'ORTH': "e'lla", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "e'lla'": [{'ORTH': "e'lla'", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "e'llai": [{'ORTH': "e'llai", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    'ella': [{'ORTH': 'ella', 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "ella'": [{'ORTH': "ella'", 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    'falla': [{'ORTH': 'falla', 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    'fallai': [{'ORTH': 'fallai', 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    'falle': [{'ORTH': 'falle', 'LEMMA': 'efallai', 'NORM': 'efallai'}],
    "'fo": [{'ORTH': "'fo", 'LEMMA': 'efo', 'NORM': 'efo'}],
    "'ishe": [{'ORTH': "'ishe", 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    "'isia": [{'ORTH': "'isia", 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    "'isio": [{'ORTH': "'isio", 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    "'sho": [{'ORTH': "'sho", 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    "'sio": [{'ORTH': "'sio", 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'eishe': [{'ORTH': 'eishe', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'eisia': [{'ORTH': 'eisia', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'eisie': [{'ORTH': 'eisie', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'ishe': [{'ORTH': 'ishe', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'ishie': [{'ORTH': 'ishie', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'ishio': [{'ORTH': 'ishio', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'isho': [{'ORTH': 'isho', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'isia': [{'ORTH': 'isia', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'isie': [{'ORTH': 'isie', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'isio': [{'ORTH': 'isio', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'moen': [{'ORTH': 'moen', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'sho': [{'ORTH': 'sho', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'sie': [{'ORTH': 'sie', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    'sio': [{'ORTH': 'sio', 'LEMMA': 'eisiau', 'NORM': 'eisiau'}],
    "'istedd": [{'ORTH': "'istedd", 'LEMMA': 'eistedd', 'NORM': 'eistedd'}],
    'eiste': [{'ORTH': 'eiste', 'LEMMA': 'eistedd', 'NORM': 'eistedd'}],
    'ishte': [{'ORTH': 'ishte', 'LEMMA': 'eistedd', 'NORM': 'eistedd'}],
    'iste': [{'ORTH': 'iste', 'LEMMA': 'eistedd', 'NORM': 'eistedd'}],
    'istedd': [{'ORTH': 'istedd', 'LEMMA': 'eistedd', 'NORM': 'eistedd'}],
    'isda': [{'ORTH': 'isda', 'LEMMA': 'eistedd', 'NORM': 'eistedda'}],
    'ishta': [{'ORTH': 'ishta', 'LEMMA': 'eistedd', 'NORM': 'eistedda'}],
    'ista': [{'ORTH': 'ista', 'LEMMA': 'eistedd', 'NORM': 'eistedda'}],
    'eitha': [{'ORTH': 'eitha', 'LEMMA': 'eithaf', 'NORM': 'eithaf'}],
    "eitha'": [{'ORTH': "eitha'", 'LEMMA': 'eithaf', 'NORM': 'eithaf'}],
    'itha': [{'ORTH': 'itha', 'LEMMA': 'eithaf', 'NORM': 'eithaf'}],
    'tha': [{'ORTH': 'tha', 'LEMMA': 'eithaf', 'NORM': 'eithaf'}],
    'thaf': [{'ORTH': 'thaf', 'LEMMA': 'eithaf', 'NORM': 'eithaf'}],
    "'leni": [{'ORTH': "'leni", 'LEMMA': 'eleni', 'NORM': 'eleni'}],
    "'lenni": [{'ORTH': "'lenni", 'LEMMA': 'eleni', 'NORM': 'eleni'}],
    'leni': [{'ORTH': 'leni', 'LEMMA': 'eleni', 'NORM': 'eleni'}],
    'elfenne': [{'ORTH': 'elfenne', 'LEMMA': 'elfen', 'NORM': 'elfennau'}],
    'eng': [{'ORTH': 'eng', 'LEMMA': 'enghraifft', 'NORM': 'enghraifft'}],
    'enghreifftie': [{'ORTH': 'enghreifftie', 'LEMMA': 'enghraifft', 'NORM': 'enghreifftiau'}],
    'enwe': [{'ORTH': 'enwe', 'LEMMA': 'enw', 'NORM': 'enwau'}],
    "'rioed": [{'ORTH': "'rioed", 'LEMMA': 'erioed', 'NORM': 'erioed'}],
    'rioed': [{'ORTH': 'rioed', 'LEMMA': 'erioed', 'NORM': 'erioed'}],
    'slawer': [{'ORTH': 'slawer', 'LEMMA': 'ers llawer', 'NORM': 'ers llawer'}],
    'sgidie': [{'ORTH': 'sgidie', 'LEMMA': 'esgid', 'NORM': 'esgidiau'}],
    "'smwytho": [{'ORTH': "'smwytho", 'LEMMA': 'esmwytho', 'NORM': 'esmwytho'}],
    'smwytho': [{'ORTH': 'smwytho', 'LEMMA': 'esmwytho', 'NORM': 'esmwytho'}],
    "fan'yn": [{'ORTH': "fan'yn", 'LEMMA': 'fan hyn', 'NORM': 'fan hyn'}],
    "fa'ma": [{'ORTH': "fa'ma", 'LEMMA': 'fan yma', 'NORM': 'fan yma'}],
    'fama': [{'ORTH': 'fama', 'LEMMA': 'fan yma', 'NORM': 'fan yma'}],
    'famma': [{'ORTH': 'famma', 'LEMMA': 'fan yma', 'NORM': 'fan yma'}],
    "f'yna": [{'ORTH': "f'yna", 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    "f'ynna": [{'ORTH': "f'ynna", 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    "fan'na": [{'ORTH': "fan'na", 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    'fana': [{'ORTH': 'fana', 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    'fanna': [{'ORTH': 'fanna', 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    'fyna': [{'ORTH': 'fyna', 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    'fynna': [{'ORTH': 'fynna', 'LEMMA': 'fan yna', 'NORM': 'fan yna'}],
    "fan'no": [{'ORTH': "fan'no", 'LEMMA': 'fan yno', 'NORM': 'fan yno'}],
    'fanno': [{'ORTH': 'fanno', 'LEMMA': 'fan yno', 'NORM': 'fan yno'}],
    "fe'l": [{'ORTH': "fe'l", 'LEMMA': "fe'l", 'NORM': "fe'l"}],
    "fel'a": [{'ORTH': "fel'a", 'LEMMA': 'fel yna', 'NORM': 'fel yna'}],
    "fel'na": [{'ORTH': "fel'na", 'LEMMA': 'fel yna', 'NORM': 'fel yna'}],
    'felna': [{'ORTH': 'felna', 'LEMMA': 'fel yna', 'NORM': 'fel yna'}],
    "'lly": [{'ORTH': "'lly", 'LEMMA': 'felly', 'NORM': 'felly'}],
    'elly': [{'ORTH': 'elly', 'LEMMA': 'felly', 'NORM': 'felly'}],
    'lly': [{'ORTH': 'lly', 'LEMMA': 'felly', 'NORM': 'felly'}],
    'ffactore': [{'ORTH': 'ffactore', 'LEMMA': 'ffactor', 'NORM': 'ffactorau'}],
    "ff'ili": [{'ORTH': "ff'ili", 'LEMMA': 'ffaelu', 'NORM': 'ffaelu'}],
    'ffili': [{'ORTH': 'ffili', 'LEMMA': 'ffaelu', 'NORM': 'ffaelu'}],
    'ffindio': [{'ORTH': 'ffindio', 'LEMMA': 'ffeindio', 'NORM': 'ffeindio'}],
    'ffenast': [{'ORTH': 'ffenast', 'LEMMA': 'ffenestr', 'NORM': 'ffenestr'}],
    'ffigyre': [{'ORTH': 'ffigyre', 'LEMMA': 'ffigwr', 'NORM': 'ffigyrau'}],
    'ffindo': [{'ORTH': 'ffindo', 'LEMMA': 'ffindio', 'NORM': 'ffindio'}],
    "ffon'o": [{'ORTH': "ffon'o", 'LEMMA': 'ffonio', 'NORM': 'ffonio'}],
    'ffor': [{'ORTH': 'ffor', 'LEMMA': 'ffordd', 'NORM': 'ffordd'}],
    "ffor'": [{'ORTH': "ffor'", 'LEMMA': 'ffordd', 'NORM': 'ffordd'}],
    'ffrindia': [{'ORTH': 'ffrindia', 'LEMMA': 'ffrind', 'NORM': 'ffrindiau'}],
    'ffrindie': [{'ORTH': 'ffrindie', 'LEMMA': 'ffrind', 'NORM': 'ffrindiau'}],
    'ffrwythe': [{'ORTH': 'ffrwythe', 'LEMMA': 'ffrwyth', 'NORM': 'ffrwythau'}],
    'finna': [{'ORTH': 'finna', 'LEMMA': 'finnau', 'NORM': 'finnau'}],
    'feirws': [{'ORTH': 'feirws', 'LEMMA': 'firws', 'NORM': 'firws'}],
    'feirysau': [{'ORTH': 'feirysau', 'LEMMA': 'firws', 'NORM': 'firysau'}],
    'forma': [{'ORTH': 'forma', 'LEMMA': 'fordd yma', 'NORM': 'fordd yma'}],
    "'y": [{'ORTH': "'y", 'LEMMA': 'fy', 'NORM': 'fy'}],
    "'ym": [{'ORTH': "'ym", 'LEMMA': 'fy', 'NORM': 'fy'}],
    "f'atgoffa": [{'ORTH': "f'atgoffa", 'LEMMA': 'fy atgoffa', 'NORM': 'fy atgoffa'}],
    "'nenu": [{'ORTH': "'nenu", 'LEMMA': 'fy nenu', 'NORM': 'fy nenu'}],
    "'nghalon": [{'ORTH': "'nghalon", 'LEMMA': 'fy nghalon', 'NORM': 'fy nghalon'}],
    "'ngollwng": [{'ORTH': "'ngollwng", 'LEMMA': 'fy ngollwng', 'NORM': 'fy ngollwng'}],
    "'ngwas": [{'ORTH': "'ngwas", 'LEMMA': 'fy ngwas', 'NORM': 'fy ngwas'}],
    "'nharo": [{'ORTH': "'nharo", 'LEMMA': 'fy nharo', 'NORM': 'fy nharo'}],
    "'nhynged": [{'ORTH': "'nhynged", 'LEMMA': 'fy nhynged', 'NORM': 'fy nhynged'}],
    "ad'el": [{'ORTH': "ad'el", 'LEMMA': 'gadael', 'NORM': 'adael'}],
    "ada'l": [{'ORTH': "ada'l", 'LEMMA': 'gadael', 'NORM': 'adael'}],
    'adal': [{'ORTH': 'adal', 'LEMMA': 'gadael', 'NORM': 'adael'}],
    'adel': [{'ORTH': 'adel', 'LEMMA': 'gadael', 'NORM': 'adael'}],
    "'ad'el": [{'ORTH': "'ad'el", 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    "'ada'l": [{'ORTH': "'ada'l", 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    "'adael": [{'ORTH': "'adael", 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    "gad'el": [{'ORTH': "gad'el", 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    "gada'l": [{'ORTH': "gada'l", 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    'gadal': [{'ORTH': 'gadal', 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    'gadel': [{'ORTH': 'gadel', 'LEMMA': 'gadael', 'NORM': 'gadael'}],
    "af'el": [{'ORTH': "af'el", 'LEMMA': 'gafael', 'NORM': 'afael'}],
    "gaf'el": [{'ORTH': "gaf'el", 'LEMMA': 'gafael', 'NORM': 'gafael'}],
    "gafa'l": [{'ORTH': "gafa'l", 'LEMMA': 'gafael', 'NORM': 'gafael'}],
    'gafal': [{'ORTH': 'gafal', 'LEMMA': 'gafael', 'NORM': 'gafael'}],
    'eirie': [{'ORTH': 'eirie', 'LEMMA': 'gair', 'NORM': 'geiriau'}],
    'geirie': [{'ORTH': 'geirie', 'LEMMA': 'gair', 'NORM': 'geiriau'}],
    "'llen": [{'ORTH': "'llen", 'LEMMA': 'gallu', 'NORM': 'allen'}],
    'allet': [{'ORTH': 'allet', 'LEMMA': 'gallu', 'NORM': 'elli'}],
    "'allu": [{'ORTH': "'allu", 'LEMMA': 'gallu', 'NORM': 'gallu'}],
    "'llu": [{'ORTH': "'llu", 'LEMMA': 'gallu', 'NORM': 'gallu'}],
    "'allwn": [{'ORTH': "'allwn", 'LEMMA': 'gallu', 'NORM': 'gallwn'}],
    'gynnach': [{'ORTH': 'gynnach', 'LEMMA': 'gan', 'NORM': 'gennych'}],
    'genai': [{'ORTH': 'genai', 'LEMMA': 'gan', 'NORM': 'gennyf'}],
    'gynnof': [{'ORTH': 'gynnof', 'LEMMA': 'gan', 'NORM': 'gennyf'}],
    'genon': [{'ORTH': 'genon', 'LEMMA': 'gan', 'NORM': 'gennym'}],
    "gynna'": [{'ORTH': "gynna'", 'LEMMA': 'gan', 'NORM': 'genyf'}],
    "ga'tre'": [{'ORTH': "ga'tre'", 'LEMMA': 'gartref', 'NORM': 'gartref'}],
    'gatre': [{'ORTH': 'gatre', 'LEMMA': 'gartref', 'NORM': 'gartref'}],
    'gema': [{'ORTH': 'gema', 'LEMMA': 'gem', 'NORM': 'gemau'}],
    'geme': [{'ORTH': 'geme', 'LEMMA': 'gem', 'NORM': 'gemau'}],
    "gyn'on": [{'ORTH': "gyn'on", 'LEMMA': 'gennym', 'NORM': 'gennym'}],
    'llnau': [{'ORTH': 'llnau', 'LEMMA': 'glanhau', 'NORM': 'glanhau'}],
    "gob'ithio": [{'ORTH': "gob'ithio", 'LEMMA': 'gobeithio', 'NORM': 'gobeithio'}],
    "gobeith'o": [{'ORTH': "gobeith'o", 'LEMMA': 'gobeithio', 'NORM': 'gobeithio'}],
    'gobeitho': [{'ORTH': 'gobeitho', 'LEMMA': 'gobeithio', 'NORM': 'gobeithio'}],
    'gola': [{'ORTH': 'gola', 'LEMMA': 'golau', 'NORM': 'golau'}],
    'gole': [{'ORTH': 'gole', 'LEMMA': 'golau', 'NORM': 'golau'}],
    'onast': [{'ORTH': 'onast', 'LEMMA': 'gonest', 'NORM': 'onest'}],
    'gorffan': [{'ORTH': 'gorffan', 'LEMMA': 'gorffen', 'NORM': 'gorffen'}],
    'orffan': [{'ORTH': 'orffan', 'LEMMA': 'gorffen', 'NORM': 'orffen'}],
    'gorffo': [{'ORTH': 'gorffo', 'LEMMA': 'gorffo', 'NORM': 'gorffo'}],
    "go'ffod": [{'ORTH': "go'ffod", 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    'goffod': [{'ORTH': 'goffod', 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    "gor'o": [{'ORTH': "gor'o", 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    "gor'o'": [{'ORTH': "gor'o'", 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    "gor'od": [{'ORTH': "gor'od", 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    'gorfo': [{'ORTH': 'gorfo', 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    'goro': [{'ORTH': 'goro', 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    'gorod': [{'ORTH': 'gorod', 'LEMMA': 'gorfod', 'NORM': 'gorfod'}],
    'radde': [{'ORTH': 'radde', 'LEMMA': 'gradd', 'NORM': 'graddau'}],
    'radda': [{'ORTH': 'radda', 'LEMMA': 'gradd', 'NORM': 'raddau'}],
    'grisia': [{'ORTH': 'grisia', 'LEMMA': 'gris', 'NORM': 'grisiau'}],
    'grwpie': [{'ORTH': 'grwpie', 'LEMMA': 'grŵp ', 'NORM': 'grwpiau'}],
    "gwahani'eth": [{'ORTH': "gwahani'eth", 'LEMMA': 'gwahaniaeth', 'NORM': 'gwahaniaeth'}],
    'gwahanieth': [{'ORTH': 'gwahanieth', 'LEMMA': 'gwahaniaeth', 'NORM': 'gwahaniaeth'}],
    "w'ithia": [{'ORTH': "w'ithia", 'LEMMA': 'gwaith', 'NORM': 'weithiau'}],
    'withia': [{'ORTH': 'withia', 'LEMMA': 'gwaith', 'NORM': 'weithiau'}],
    'gwallgo': [{'ORTH': 'gwallgo', 'LEMMA': 'gwallgof', 'NORM': 'gwallgof'}],
    'wallgo': [{'ORTH': 'wallgo', 'LEMMA': 'gwallgof', 'NORM': 'wallgof'}],
    "gwasan'eth": [{'ORTH': "gwasan'eth", 'LEMMA': 'gwasanaeth', 'NORM': 'gwasanaeth'}],
    'gwasaneth': [{'ORTH': 'gwasaneth', 'LEMMA': 'gwasanaeth', 'NORM': 'gwasanaeth'}],
    'gwasanaethe': [{'ORTH': 'gwasanaethe', 'LEMMA': 'gwasanaeth', 'NORM': 'gwasanaethau'}],
    'gwddwg': [{'ORTH': 'gwddwg', 'LEMMA': 'gwddw', 'NORM': 'gwddw'}],
    'gweithgaredda': [{'ORTH': 'gweithgaredda', 'LEMMA': 'gweithgaredd', 'NORM': 'gweithgareddau'}],
    'gweithgaredde': [{'ORTH': 'gweithgaredde', 'LEMMA': 'gweithgaredd', 'NORM': 'gweithgareddau'}],
    "gw'ithio": [{'ORTH': "gw'ithio", 'LEMMA': 'gweithio', 'NORM': 'gweithio'}],
    "gweith'o": [{'ORTH': "gweith'o", 'LEMMA': 'gweithio', 'NORM': 'gweithio'}],
    'gweitho': [{'ORTH': 'gweitho', 'LEMMA': 'gweithio', 'NORM': 'gweithio'}],
    'gwithio': [{'ORTH': 'gwithio', 'LEMMA': 'gweithio', 'NORM': 'gweithio'}],
    'gwitho': [{'ORTH': 'gwitho', 'LEMMA': 'gweithio', 'NORM': 'gweithio'}],
    'gwela': [{'ORTH': 'gwela', 'LEMMA': 'gweld', 'NORM': 'gwelaf'}],
    "gwela'": [{'ORTH': "gwela'", 'LEMMA': 'gweld', 'NORM': 'gwelaf'}],
    'gwel': [{'ORTH': 'gwel', 'LEMMA': 'gweld', 'NORM': 'gweld'}],
    "gwel'": [{'ORTH': "gwel'", 'LEMMA': 'gweld', 'NORM': 'gweld'}],
    'wela': [{'ORTH': 'wela', 'LEMMA': 'gweld', 'NORM': 'welaf'}],
    "wela'": [{'ORTH': "wela'", 'LEMMA': 'gweld', 'NORM': 'welaf'}],
    'welo': [{'ORTH': 'welo', 'LEMMA': 'gweld', 'NORM': 'welom'}],
    "welo'": [{'ORTH': "welo'", 'LEMMA': 'gweld', 'NORM': 'welon'}],
    'welson': [{'ORTH': 'welson', 'LEMMA': 'gweld', 'NORM': 'welsom'}],
    'wch': [{'ORTH': 'wch', 'LEMMA': 'gwelwch chi', 'NORM': 'gwelwch chi'}],
    'ylwch': [{'ORTH': 'ylwch', 'LEMMA': 'gwelwch chi', 'NORM': 'gwelwch chi'}],
    'tsiecio': [{'ORTH': 'tsiecio', 'LEMMA': 'gwirio', 'NORM': 'gwirio'}],
    "'wisgo": [{'ORTH': "'wisgo", 'LEMMA': 'gwisgo', 'NORM': 'gwisgo'}],
    "na'thon": [{'ORTH': "na'thon", 'LEMMA': 'gwnaethon', 'NORM': 'wnaethon'}],
    'nawni': [{'ORTH': 'nawni', 'LEMMA': 'gwnawn ni', 'NORM': 'gwnawn ni'}],
    'naeth': [{'ORTH': 'naeth', 'LEMMA': 'gwneud', 'NORM': 'gwnaeth'}],
    'nath': [{'ORTH': 'nath', 'LEMMA': 'gwneud', 'NORM': 'gwnaeth'}],
    'naethoch': [{'ORTH': 'naethoch', 'LEMMA': 'gwneud', 'NORM': 'gwnaethoch'}],
    'naethon': [{'ORTH': 'naethon', 'LEMMA': 'gwneud', 'NORM': 'gwnaethon'}],
    "'na'": [{'ORTH': "'na'", 'LEMMA': 'gwneud', 'NORM': 'gwnaf'}],
    'nai': [{'ORTH': 'nai', 'LEMMA': 'gwneud', 'NORM': 'gwnaf'}],
    'wnai': [{'ORTH': 'wnai', 'LEMMA': 'gwneud', 'NORM': 'gwnaf'}],
    'neiff': [{'ORTH': 'neiff', 'LEMMA': 'gwneud', 'NORM': 'gwnaiff'}],
    'neith': [{'ORTH': 'neith', 'LEMMA': 'gwneud', 'NORM': 'gwnaiff'}],
    "'nawn": [{'ORTH': "'nawn", 'LEMMA': 'gwneud', 'NORM': 'gwnawn'}],
    "'newn": [{'ORTH': "'newn", 'LEMMA': 'gwneud', 'NORM': 'gwnawn'}],
    'newn': [{'ORTH': 'newn', 'LEMMA': 'gwneud', 'NORM': 'gwnawn'}],
    "'nei": [{'ORTH': "'nei", 'LEMMA': 'gwneud', 'NORM': 'gwnei'}],
    "'nes": [{'ORTH': "'nes", 'LEMMA': 'gwneud', 'NORM': 'gwnes'}],
    "'wnes": [{'ORTH': "'wnes", 'LEMMA': 'gwneud', 'NORM': 'gwnes'}],
    'neshi': [{'ORTH': 'neshi', 'LEMMA': 'gwneud', 'NORM': 'gwnes'}],
    "'neud": [{'ORTH': "'neud", 'LEMMA': 'gwneud', 'NORM': 'gwneud'}],
    "g'neud": [{'ORTH': "g'neud", 'LEMMA': 'gwneud', 'NORM': 'gwneud'}],
    'gneud': [{'ORTH': 'gneud', 'LEMMA': 'gwneud', 'NORM': 'gwneud'}],
    'neud': [{'ORTH': 'neud', 'LEMMA': 'gwneud', 'NORM': 'gwneud'}],
    "'newch": [{'ORTH': "'newch", 'LEMMA': 'gwneud', 'NORM': 'gwnewch'}],
    'newch': [{'ORTH': 'newch', 'LEMMA': 'gwneud', 'NORM': 'gwnewch'}],
    "'na'th": [{'ORTH': "'na'th", 'LEMMA': 'gwneud', 'NORM': 'wnaeth'}],
    "'na'than": [{'ORTH': "'na'than", 'LEMMA': 'gwneud', 'NORM': 'wnaethom'}],
    "'na'thon": [{'ORTH': "'na'thon", 'LEMMA': 'gwneud', 'NORM': 'wnaethom'}],
    "'nathan": [{'ORTH': "'nathan", 'LEMMA': 'gwneud', 'NORM': 'wnaethom'}],
    "'nathon": [{'ORTH': "'nathon", 'LEMMA': 'gwneud', 'NORM': 'wnaethom'}],
    'nathon': [{'ORTH': 'nathon', 'LEMMA': 'gwneud', 'NORM': 'wnaethon'}],
    'nawn': [{'ORTH': 'nawn', 'LEMMA': 'gwneud', 'NORM': 'wnawn'}],
    'nei': [{'ORTH': 'nei', 'LEMMA': 'gwneud', 'NORM': 'wnei'}],
    "neu'": [{'ORTH': "neu'", 'LEMMA': 'gwneud', 'NORM': 'wneud'}],
    'neithi': [{'ORTH': 'neithi', 'LEMMA': 'gwneud hi', 'NORM': 'gwnaiff hi'}],
    "g'rando": [{'ORTH': "g'rando", 'LEMMA': 'gwrando', 'NORM': 'gwrando'}],
    'gwrando': [{'ORTH': 'gwrando', 'LEMMA': 'gwrando', 'NORM': 'gwrando'}],
    "'bo": [{'ORTH': "'bo", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "'bo'": [{'ORTH': "'bo'", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "'bod": [{'ORTH': "'bod", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "'w'bod": [{'ORTH': "'w'bod", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "'wbod": [{'ORTH': "'wbod", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "gw'bo": [{'ORTH': "gw'bo", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "gw'bo'": [{'ORTH': "gw'bo'", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "gw'bod": [{'ORTH': "gw'bod", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    'gwbo': [{'ORTH': 'gwbo', 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    'gwbod': [{'ORTH': 'gwbod', 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    'gwybo': [{'ORTH': 'gwybo', 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "gwybo'": [{'ORTH': "gwybo'", 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    'wbod': [{'ORTH': 'wbod', 'LEMMA': 'gwybod', 'NORM': 'gwybod'}],
    "w'bod": [{'ORTH': "w'bod", 'LEMMA': 'gwybod', 'NORM': 'wybod'}],
    "w'sti": [{'ORTH': "w'sti", 'LEMMA': 'gwybod ti', 'NORM': 'wyddost ti'}],
    'wsti': [{'ORTH': 'wsti', 'LEMMA': 'gwybod ti', 'NORM': 'wyddost ti'}],
    "'mo'r": [{'ORTH': "'mo'r", 'LEMMA': 'gwybod yr', 'NORM': 'gwybod yr'}],
    "gwybod'eth": [{'ORTH': "gwybod'eth", 'LEMMA': 'gwybodaeth', 'NORM': 'gwybodaeth'}],
    'gwybodeth': [{'ORTH': 'gwybodeth', 'LEMMA': 'gwybodaeth', 'NORM': 'gwybodaeth'}],
    'gwylie': [{'ORTH': 'gwylie', 'LEMMA': 'gwyliau', 'NORM': 'gwyliau'}],
    'wylie': [{'ORTH': 'wylie', 'LEMMA': 'gwyliau', 'NORM': 'wyliau'}],
    'gwatsiad': [{'ORTH': 'gwatsiad', 'LEMMA': 'gwylio', 'NORM': 'gwylio'}],
    'watsiad': [{'ORTH': 'watsiad', 'LEMMA': 'gwylio', 'NORM': 'gwylio'}],
    "ha'": [{'ORTH': "ha'", 'LEMMA': 'haf', 'NORM': 'haf'}],
    'hanas': [{'ORTH': 'hanas', 'LEMMA': 'hanes', 'NORM': 'hanes'}],
    'hannar': [{'ORTH': 'hannar', 'LEMMA': 'hanner', 'NORM': 'hanner'}],
    'hawlie': [{'ORTH': 'hawlie', 'LEMMA': 'hawl', 'NORM': 'hawliau'}],
    'blaw': [{'ORTH': 'blaw', 'LEMMA': 'heb law', 'NORM': 'heb law'}],
    'heddi': [{'ORTH': 'heddi', 'LEMMA': 'heddiw', 'NORM': 'heddiw'}],
    "heddi'": [{'ORTH': "heddi'", 'LEMMA': 'heddiw', 'NORM': 'heddiw'}],
    "'efyd": [{'ORTH': "'efyd", 'LEMMA': 'hefyd', 'NORM': 'hefyd'}],
    "'fyd": [{'ORTH': "'fyd", 'LEMMA': 'hefyd', 'NORM': 'hefyd'}],
    'ed': [{'ORTH': 'ed', 'LEMMA': 'hefyd', 'NORM': 'hefyd'}],
    'efyd': [{'ORTH': 'efyd', 'LEMMA': 'hefyd', 'NORM': 'hefyd'}],
    'hitha': [{'ORTH': 'hitha', 'LEMMA': 'hithau', 'NORM': 'hithau'}],
    'hithe': [{'ORTH': 'hithe', 'LEMMA': 'hithau', 'NORM': 'hithau'}],
    'genod': [{'ORTH': 'genod', 'LEMMA': 'hogen', 'NORM': 'hogenod'}],
    'hogia': [{'ORTH': 'hogia', 'LEMMA': 'hogyn', 'NORM': 'hogiau'}],
    "'onna": [{'ORTH': "'onna", 'LEMMA': 'honna', 'NORM': 'honna'}],
    "'unan": [{'ORTH': "'unan", 'LEMMA': 'hunan', 'NORM': 'hunan'}],
    'unan': [{'ORTH': 'unan', 'LEMMA': 'hunan', 'NORM': 'hunan'}],
    'hwne': [{'ORTH': 'hwne', 'LEMMA': 'hwn', 'NORM': 'hwnna'}],
    'nna': [{'ORTH': 'nna', 'LEMMA': 'hwnna', 'NORM': 'hwnna'}],
    'wnna': [{'ORTH': 'wnna', 'LEMMA': 'hwnna', 'NORM': 'hwnna'}],
    "'w'rach": [{'ORTH': "'w'rach", 'LEMMA': 'hwyr', 'NORM': 'hwyrach'}],
    "w'rach": [{'ORTH': "w'rach", 'LEMMA': 'hwyrach', 'NORM': 'hwyrach'}],
    'wyrach': [{'ORTH': 'wyrach', 'LEMMA': 'hwyrh', 'NORM': 'hwyrach'}],
    "'nny": [{'ORTH': "'nny", 'LEMMA': 'hynny', 'NORM': 'hynny'}],
    "'ny": [{'ORTH': "'ny", 'LEMMA': 'hynny', 'NORM': 'hynny'}],
    'hynne': [{'ORTH': 'hynne', 'LEMMA': 'hynny', 'NORM': 'hynny'}],
    'nny': [{'ORTH': 'nny', 'LEMMA': 'hynny', 'NORM': 'hynny'}],
    'ny': [{'ORTH': 'ny', 'LEMMA': 'hynny', 'NORM': 'hynny'}],
    'ynny': [{'ORTH': 'ynny', 'LEMMA': 'hynny', 'NORM': 'hynny'}],
    'ith': [{'ORTH': 'ith', 'LEMMA': 'i dy', 'NORM': 'i dy'}],
    "i'chi": [{'ORTH': "i'chi", 'LEMMA': "i'chi", 'NORM': "i'chi"}],
    "i'": [{'ORTH': "i'", 'LEMMA': "i'w", 'NORM': "i'w"}],
    'iw': [{'ORTH': 'iw', 'LEMMA': "i'w", 'NORM': "i'w"}],
    "i'ni": [{'ORTH': "i'ni", 'LEMMA': 'iddon ni', 'NORM': 'iddon ni'}],
    'ifenc': [{'ORTH': 'ifenc', 'LEMMA': 'ifanc', 'NORM': 'ifanc'}],
    'isa': [{'ORTH': 'isa', 'LEMMA': 'isel', 'NORM': 'isaf'}],
    'jes': [{'ORTH': 'jes', 'LEMMA': 'jest', 'NORM': 'jest'}],
    'jesd': [{'ORTH': 'jesd', 'LEMMA': 'jest', 'NORM': 'jest'}],
    'jysd': [{'ORTH': 'jysd', 'LEMMA': 'jest', 'NORM': 'jest'}],
    "lic'o": [{'ORTH': "lic'o", 'LEMMA': 'licio', 'NORM': 'licio'}],
    'lico': [{'ORTH': 'lico', 'LEMMA': 'licio', 'NORM': 'licio'}],
    'llawar': [{'ORTH': 'llawar', 'LEMMA': 'llawer', 'NORM': 'llawer'}],
    "'le": [{'ORTH': "'le", 'LEMMA': 'lle', 'NORM': 'lle'}],
    'leia': [{'ORTH': 'leia', 'LEMMA': 'lleiaf', 'NORM': 'leiaf'}],
    "leia'": [{'ORTH': "leia'", 'LEMMA': 'lleiaf', 'NORM': 'leiaf'}],
    'lleia': [{'ORTH': 'lleia', 'LEMMA': 'lleiaf', 'NORM': 'lleiaf'}],
    'lliwie': [{'ORTH': 'lliwie', 'LEMMA': 'lliw', 'NORM': 'lliwiau'}],
    'lunie': [{'ORTH': 'lunie', 'LEMMA': 'llun', 'NORM': 'luniau'}],
    'llyfre': [{'ORTH': 'llyfre', 'LEMMA': 'llyfr', 'NORM': 'llyfrau'}],
    'lyfre': [{'ORTH': 'lyfre', 'LEMMA': 'llyfr', 'NORM': 'lyfrau'}],
    'llyged': [{'ORTH': 'llyged', 'LEMMA': 'llygad', 'NORM': 'llygaid'}],
    'llynia': [{'ORTH': 'llynia', 'LEMMA': 'llyn', 'NORM': 'llyniau'}],
    'llynadd': [{'ORTH': 'llynadd', 'LEMMA': 'llynedd', 'NORM': 'llynedd'}],
    "llywodr'eth": [{'ORTH': "llywodr'eth", 'LEMMA': 'llywodraeth', 'NORM': 'llywodraeth'}],
    'llywodreth': [{'ORTH': 'llywodreth', 'LEMMA': 'llywodraeth', 'NORM': 'llywodraeth'}],
    'mham': [{'ORTH': 'mham', 'LEMMA': 'mam', 'NORM': 'mam'}],
    "Fa'": [{'ORTH': "Fa'", 'LEMMA': 'man', 'NORM': 'fan'}],
    "fa'": [{'ORTH': "fa'", 'LEMMA': 'man', 'NORM': 'fan'}],
    'marcie': [{'ORTH': 'marcie', 'LEMMA': 'marc', 'NORM': 'marciau'}],
    'fowr': [{'ORTH': 'fowr', 'LEMMA': 'mawr', 'NORM': 'mawr'}],
    'mowr': [{'ORTH': 'mowr', 'LEMMA': 'mawr', 'NORM': 'mawr'}],
    'mwya': [{'ORTH': 'mwya', 'LEMMA': 'mawr', 'NORM': 'mwyaf'}],
    "mwya'": [{'ORTH': "mwya'", 'LEMMA': 'mawr', 'NORM': 'mwyaf'}],
    "me'l": [{'ORTH': "me'l", 'LEMMA': 'meddwl', 'NORM': 'meddwl'}],
    "me'wl": [{'ORTH': "me'wl", 'LEMMA': 'meddwl', 'NORM': 'meddwl'}],
    'meddylie': [{'ORTH': 'meddylie', 'LEMMA': 'meddwl', 'NORM': 'meddyliau'}],
    'fedar': [{'ORTH': 'fedar', 'LEMMA': 'medru', 'NORM': 'fedr'}],
    'fedra': [{'ORTH': 'fedra', 'LEMMA': 'medru', 'NORM': 'fedraf'}],
    "fedra'": [{'ORTH': "fedra'", 'LEMMA': 'medru', 'NORM': 'fedraf'}],
    'miwn': [{'ORTH': 'miwn', 'LEMMA': 'mewn', 'NORM': 'mewn'}],
    'feicroffon': [{'ORTH': 'feicroffon', 'LEMMA': 'microffon', 'NORM': 'ficroffon'}],
    'feicroffonau': [{'ORTH': 'feicroffonau', 'LEMMA': 'microffon', 'NORM': 'ficroffonau'}],
    'meicroffon': [{'ORTH': 'meicroffon', 'LEMMA': 'microffon', 'NORM': 'microffon'}],
    'meicroffonau': [{'ORTH': 'meicroffonau', 'LEMMA': 'microffon', 'NORM': 'microffonau'}],
    'finne': [{'ORTH': 'finne', 'LEMMA': 'minnau', 'NORM': 'finnau'}],
    "finne'": [{'ORTH': "finne'", 'LEMMA': 'minnau', 'NORM': 'finnau'}],
    'minna': [{'ORTH': 'minna', 'LEMMA': 'minnau', 'NORM': 'minnau'}],
    'mish': [{'ORTH': 'mish', 'LEMMA': 'mis', 'NORM': 'mis'}],
    'modiwle': [{'ORTH': 'modiwle', 'LEMMA': 'modiwl', 'NORM': 'modiwlau'}],
    "mo'yn": [{'ORTH': "mo'yn", 'LEMMA': 'mofyn', 'NORM': 'mofyn'}],
    'moyn': [{'ORTH': 'moyn', 'LEMMA': 'mofyn', 'NORM': 'mofyn'}],
    'fwya': [{'ORTH': 'fwya', 'LEMMA': 'mwy', 'NORM': 'fwyaf'}],
    "a'th": [{'ORTH': "a'th", 'LEMMA': 'mynd', 'NORM': 'aeth'}],
    'ethon': [{'ORTH': 'ethon', 'LEMMA': 'mynd', 'NORM': 'aethon'}],
    "a'": [{'ORTH': "a'", 'LEMMA': 'mynd', 'NORM': 'af'}],
    'ewn': [{'ORTH': 'ewn', 'LEMMA': 'mynd', 'NORM': 'awn'}],
    'esh': [{'ORTH': 'esh', 'LEMMA': 'mynd', 'NORM': 'es'}],
    'myned': [{'ORTH': 'myned', 'LEMMA': 'mynd', 'NORM': 'mynd'}],
    'nagoes': [{'ORTH': 'nagoes', 'LEMMA': 'nac oes', 'NORM': 'nac oes'}],
    'nacdi': [{'ORTH': 'nacdi', 'LEMMA': 'nac ydy', 'NORM': 'nac ydy'}],
    'nachdi': [{'ORTH': 'nachdi', 'LEMMA': 'nac ydy', 'NORM': 'nac ydy'}],
    'nagyn': [{'ORTH': 'nagyn', 'LEMMA': 'nac ydyn', 'NORM': 'nac ydyn'}],
    'nagyw': [{'ORTH': 'nagyw', 'LEMMA': 'nac yw', 'NORM': 'nac yw'}],
    'nagoedd': [{'ORTH': 'nagoedd', 'LEMMA': 'nag oedd', 'NORM': 'nag oedd'}],
    'negas': [{'ORTH': 'negas', 'LEMMA': 'neges', 'NORM': 'neges'}],
    'nithwr': [{'ORTH': 'nithwr', 'LEMMA': 'neithiwr', 'NORM': 'neithiwr'}],
    'nesa': [{'ORTH': 'nesa', 'LEMMA': 'nesaf', 'NORM': 'nesaf'}],
    "nesa'": [{'ORTH': "nesa'", 'LEMMA': 'nesaf', 'NORM': 'nesaf'}],
    "Ne'": [{'ORTH': "Ne'", 'LEMMA': 'neu', 'NORM': 'neu'}],
    'ne': [{'ORTH': 'ne', 'LEMMA': 'neu', 'NORM': 'neu'}],
    "ne'": [{'ORTH': "ne'", 'LEMMA': 'neu', 'NORM': 'neu'}],
    'newidiade': [{'ORTH': 'newidiade', 'LEMMA': 'newid', 'NORM': 'newidiadau'}],
    'newy': [{'ORTH': 'newy', 'LEMMA': 'newydd', 'NORM': 'newydd'}],
    "newy'": [{'ORTH': "newy'", 'LEMMA': 'newydd', 'NORM': 'newydd'}],
    'nw': [{'ORTH': 'nw', 'LEMMA': 'nhw', 'NORM': 'nhw'}],
    'nhwn': [{'ORTH': 'nhwn', 'LEMMA': 'nhw yn', 'NORM': 'nhw yn'}],
    'ninna': [{'ORTH': 'ninna', 'LEMMA': 'ni', 'NORM': 'ninnau'}],
    "'d": [{'ORTH': "'d", 'LEMMA': 'nid', 'NORM': 'nid'}],
    "d'oedd": [{'ORTH': "d'oedd", 'LEMMA': 'nid oedd', 'NORM': 'nid oedd'}],
    'doedd': [{'ORTH': 'doedd', 'LEMMA': 'nid oedd', 'NORM': 'nid oedd'}],
    "s'gen": [{'ORTH': "s'gen", 'LEMMA': 'nid oes gen', 'NORM': 'nid oes gen'}],
    'tydw': [{'ORTH': 'tydw', 'LEMMA': 'nid ydw', 'NORM': 'nid ydw'}],
    'dydan': [{'ORTH': 'dydan', 'LEMMA': 'nid ydyn', 'NORM': 'nid ydyn'}],
    "d'yw": [{'ORTH': "d'yw", 'LEMMA': 'nid yw', 'NORM': 'nid yw'}],
    'nodiade': [{'ORTH': 'nodiade', 'LEMMA': 'nodiad', 'NORM': 'nodiadau'}],
    'nosweth': [{'ORTH': 'nosweth', 'LEMMA': 'noswaith', 'NORM': 'noswaith'}],
    "o'noch": [{'ORTH': "o'noch", 'LEMMA': 'o', 'NORM': 'ohonoch'}],
    'ohonach': [{'ORTH': 'ohonach', 'LEMMA': 'o', 'NORM': 'ohonoch'}],
    'onoch': [{'ORTH': 'onoch', 'LEMMA': 'o', 'NORM': 'ohonoch'}],
    "o'nyn": [{'ORTH': "o'nyn", 'LEMMA': 'o', 'NORM': 'ohonynt'}],
    'onyn': [{'ORTH': 'onyn', 'LEMMA': 'o', 'NORM': 'ohonynt'}],
    'oleia': [{'ORTH': 'oleia', 'LEMMA': 'o leiaf', 'NORM': 'o leiaf'}],
    'oddiwrth': [{'ORTH': 'oddiwrth', 'LEMMA': 'oddi wrth', 'NORM': 'oddi wrth'}],
    'oddo': [{'ORTH': 'oddo', 'LEMMA': 'oedd o', 'NORM': 'oedd o'}],
    'sgen': [{'ORTH': 'sgen', 'LEMMA': 'oes gen', 'NORM': 'oes gen'}],
    'ofan': [{'ORTH': 'ofan', 'LEMMA': 'ofn', 'NORM': 'ofn'}],
    'ofon': [{'ORTH': 'ofon', 'LEMMA': 'ofn', 'NORM': 'ofn'}],
    'ofnadw': [{'ORTH': 'ofnadw', 'LEMMA': 'ofnadwy', 'NORM': 'ofnadwy'}],
    "ofnadw'": [{'ORTH': "ofnadw'", 'LEMMA': 'ofnadwy', 'NORM': 'ofnadwy'}],
    'ola': [{'ORTH': 'ola', 'LEMMA': 'olaf', 'NORM': 'olaf'}],
    "ola'": [{'ORTH': "ola'", 'LEMMA': 'olaf', 'NORM': 'olaf'}],
    'onibai': [{'ORTH': 'onibai', 'LEMMA': 'oni bai', 'NORM': 'oni bai'}],
    'ynd': [{'ORTH': 'ynd', 'LEMMA': 'onid', 'NORM': 'onid'}],
    "'de": [{'ORTH': "'de", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    "'i'fe": [{'ORTH': "'i'fe", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    "'n'de": [{'ORTH': "'n'de", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    "'n'efe": [{'ORTH': "'n'efe", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    "d'e": [{'ORTH': "d'e", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    'ife': [{'ORTH': 'ife', 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    'nde': [{'ORTH': 'nde', 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    'nefe': [{'ORTH': 'nefe', 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    "yn'de": [{'ORTH': "yn'de", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    "ynd'e": [{'ORTH': "ynd'e", 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    'ynde': [{'ORTH': 'ynde', 'LEMMA': 'onid ef', 'NORM': 'onid ef'}],
    'dyfe': [{'ORTH': 'dyfe', 'LEMMA': 'onid efe', 'NORM': 'onid efe'}],
    'dê': [{'ORTH': 'dê', 'LEMMA': 'onid efe', 'NORM': 'onid efe'}],
    'yndefe': [{'ORTH': 'yndefe', 'LEMMA': 'onid efe', 'NORM': 'onid efe'}],
    'yndyfe': [{'ORTH': 'yndyfe', 'LEMMA': 'onid efe', 'NORM': 'onid efe'}],
    'yndê': [{'ORTH': 'yndê', 'LEMMA': 'onid efe', 'NORM': 'onid efe'}],
    'yntê': [{'ORTH': 'yntê', 'LEMMA': 'onid efe', 'NORM': 'onid efe'}],
    'yndoedd': [{'ORTH': 'yndoedd', 'LEMMA': 'onid oedd', 'NORM': 'onid doedd'}],
    "d'oes": [{'ORTH': "d'oes", 'LEMMA': 'onid oes', 'NORM': 'onid oes'}],
    'yndoes': [{'ORTH': 'yndoes', 'LEMMA': 'onid oes', 'NORM': 'onid oes'}],
    "'dydi": [{'ORTH': "'dydi", 'LEMMA': 'onid ydy', 'NORM': 'onid ydy'}],
    'ndi': [{'ORTH': 'ndi', 'LEMMA': 'onid ydy', 'NORM': 'onid ydy'}],
    'tydy': [{'ORTH': 'tydy', 'LEMMA': 'onid ydy', 'NORM': 'onid ydy'}],
    'yndydy': [{'ORTH': 'yndydy', 'LEMMA': 'onid ydy', 'NORM': 'onid ydy'}],
    'yntydi': [{'ORTH': 'yntydi', 'LEMMA': 'onid ydy', 'NORM': 'onid ydy'}],
    'tydyn': [{'ORTH': 'tydyn', 'LEMMA': 'onid ydyn', 'NORM': 'onid ydyn'}],
    'yndydi': [{'ORTH': 'yndydi', 'LEMMA': 'onid yw', 'NORM': 'onid yw'}],
    'otsh': [{'ORTH': 'otsh', 'LEMMA': 'ots', 'NORM': 'ots'}],
    "p'": [{'ORTH': "p'", 'LEMMA': 'pa', 'NORM': 'pa'}],
    'prun': [{'ORTH': 'prun', 'LEMMA': 'pa rhyw un', 'NORM': 'pa ryw un'}],
    "p'run": [{'ORTH': "p'run", 'LEMMA': 'pa un', 'NORM': 'pa un'}],
    "p'un": [{'ORTH': "p'un", 'LEMMA': 'pa un', 'NORM': 'pa un'}],
    'pun': [{'ORTH': 'pun', 'LEMMA': 'pa un', 'NORM': 'pa un'}],
    'papure': [{'ORTH': 'papure', 'LEMMA': 'papur', 'NORM': 'papurau'}],
    'powb': [{'ORTH': 'powb', 'LEMMA': 'pawb', 'NORM': 'pawb'}],
    'peirianne': [{'ORTH': 'peirianne', 'LEMMA': 'peiriant', 'NORM': 'peiriannau'}],
    'penne': [{'ORTH': 'penne', 'LEMMA': 'pen', 'NORM': 'pennau'}],
    'bentre': [{'ORTH': 'bentre', 'LEMMA': 'pentref', 'NORM': 'bentref'}],
    'pentra': [{'ORTH': 'pentra', 'LEMMA': 'pentref', 'NORM': 'pentref'}],
    'pentre': [{'ORTH': 'pentre', 'LEMMA': 'pentref', 'NORM': 'pentref'}],
    "penw'thnos": [{'ORTH': "penw'thnos", 'LEMMA': 'penwythnos', 'NORM': 'penwythnos'}],
    'penwthnos': [{'ORTH': 'penwthnos', 'LEMMA': 'penwythnos', 'NORM': 'penwythnos'}],
    'tase': [{'ORTH': 'tase', 'LEMMA': 'petai', 'NORM': 'petase'}],
    'betha': [{'ORTH': 'betha', 'LEMMA': 'peth', 'NORM': 'bethau'}],
    'petha': [{'ORTH': 'petha', 'LEMMA': 'peth', 'NORM': 'pethau'}],
    'pleidie': [{'ORTH': 'pleidie', 'LEMMA': 'plaid', 'NORM': 'pleidiau'}],
    'broblam': [{'ORTH': 'broblam', 'LEMMA': 'problem', 'NORM': 'broblem'}],
    'brobleme': [{'ORTH': 'brobleme', 'LEMMA': 'problem', 'NORM': 'broblemau'}],
    'problam': [{'ORTH': 'problam', 'LEMMA': 'problem', 'NORM': 'problem'}],
    'problema': [{'ORTH': 'problema', 'LEMMA': 'problem', 'NORM': 'problemau'}],
    'probleme': [{'ORTH': 'probleme', 'LEMMA': 'problem', 'NORM': 'problemau'}],
    "b'nawn": [{'ORTH': "b'nawn", 'LEMMA': 'prynhawn', 'NORM': 'brynhawn'}],
    'bnawn': [{'ORTH': 'bnawn', 'LEMMA': 'prynhawn', 'NORM': 'brynhawn'}],
    "p'nawn": [{'ORTH': "p'nawn", 'LEMMA': 'prynhawn', 'NORM': 'prynhawn'}],
    'pnawn': [{'ORTH': 'pnawn', 'LEMMA': 'prynhawn', 'NORM': 'prynhawn'}],
    'bunne': [{'ORTH': 'bunne', 'LEMMA': 'punnau', 'NORM': 'bunnau'}],
    'bunna': [{'ORTH': 'bunna', 'LEMMA': 'punt', 'NORM': 'bunnau'}],
    "pw'": [{'ORTH': "pw'", 'LEMMA': 'pwy', 'NORM': 'pwy'}],
    'bwyntie': [{'ORTH': 'bwyntie', 'LEMMA': 'pwynt', 'NORM': 'bwyntiau'}],
    'pwyntie': [{'ORTH': 'pwyntie', 'LEMMA': 'pwynt', 'NORM': 'pwyntiau'}],
    'bwyse': [{'ORTH': 'bwyse', 'LEMMA': 'pwys', 'NORM': 'bwysau'}],
    'pwyse': [{'ORTH': 'pwyse', 'LEMMA': 'pwys', 'NORM': 'pwysau'}],
    'recordo': [{'ORTH': 'recordo', 'LEMMA': 'recordio', 'NORM': 'recordio'}],
    "'ag": [{'ORTH': "'ag", 'LEMMA': 'rhag', 'NORM': 'rhag'}],
    'cofn': [{'ORTH': 'cofn', 'LEMMA': 'rhag ofn', 'NORM': 'rhag ofn'}],
    'rhei': [{'ORTH': 'rhei', 'LEMMA': 'rhai', 'NORM': 'rhai'}],
    "rai'": [{'ORTH': "rai'", 'LEMMA': 'rhaid', 'NORM': 'raid'}],
    "r'aid": [{'ORTH': "r'aid", 'LEMMA': 'rhaid', 'NORM': 'rhaid'}],
    "rhai'": [{'ORTH': "rhai'", 'LEMMA': 'rhaid', 'NORM': 'rhaid'}],
    "'hein": [{'ORTH': "'hein", 'LEMMA': 'rhain', 'NORM': 'rhain'}],
    'hein': [{'ORTH': 'hein', 'LEMMA': 'rhain', 'NORM': 'rhain'}],
    'rhein': [{'ORTH': 'rhein', 'LEMMA': 'rhain', 'NORM': 'rhain'}],
    "'heina": [{'ORTH': "'heina", 'LEMMA': 'rhain', 'NORM': 'rheina'}],
    'heina': [{'ORTH': 'heina', 'LEMMA': 'rhain', 'NORM': 'rheina'}],
    'rhanne': [{'ORTH': 'rhanne', 'LEMMA': 'rhan', 'NORM': 'rhannau'}],
    'rhedag': [{'ORTH': 'rhedag', 'LEMMA': 'rhedeg', 'NORM': 'rhedeg'}],
    'rheole': [{'ORTH': 'rheole', 'LEMMA': 'rheol', 'NORM': 'rheolau'}],
    'resyme': [{'ORTH': 'resyme', 'LEMMA': 'rheswm', 'NORM': 'resymau'}],
    'rhesyme': [{'ORTH': 'rhesyme', 'LEMMA': 'rheswm', 'NORM': 'rhesymau'}],
    "r'oi": [{'ORTH': "r'oi", 'LEMMA': 'rhoi', 'NORM': 'rhoi'}],
    "r'oid": [{'ORTH': "r'oid", 'LEMMA': 'rhoi', 'NORM': 'rhoi'}],
    'rhyfadd': [{'ORTH': 'rhyfadd', 'LEMMA': 'rhyfeadd', 'NORM': 'rhyfedd'}],
    "r'yw": [{'ORTH': "r'yw", 'LEMMA': 'rhyw', 'NORM': 'rhyw'}],
    'rw': [{'ORTH': 'rw', 'LEMMA': 'rhyw', 'NORM': 'rhyw'}],
    'ryw': [{'ORTH': 'ryw', 'LEMMA': 'rhyw', 'NORM': 'rhyw'}],
    'rhywfath': [{'ORTH': 'rhywfath', 'LEMMA': 'rhyw fath', 'NORM': 'rhyw fath'}],
    "'bath": [{'ORTH': "'bath", 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    "r'wbath": [{'ORTH': "r'wbath", 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    "rh'wbath": [{'ORTH': "rh'wbath", 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    "rh'wbeth": [{'ORTH': "rh'wbeth", 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    'rhwbath': [{'ORTH': 'rhwbath', 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    'rhwbeth': [{'ORTH': 'rhwbeth', 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    'rwbath': [{'ORTH': 'rwbath', 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    'wbath': [{'ORTH': 'wbath', 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    'wbeth': [{'ORTH': 'wbeth', 'LEMMA': 'rhywbeth', 'NORM': 'rhywbeth'}],
    "r'wbeth": [{'ORTH': "r'wbeth", 'LEMMA': 'rhywbeth', 'NORM': 'rywbeth'}],
    'rwbeth': [{'ORTH': 'rwbeth', 'LEMMA': 'rhywbeth', 'NORM': 'rywbeth'}],
    'rhywffor': [{'ORTH': 'rhywffor', 'LEMMA': 'rhywffordd', 'NORM': 'rhywffordd'}],
    "rhywffor'": [{'ORTH': "rhywffor'", 'LEMMA': 'rhywffordd', 'NORM': 'rhywffordd'}],
    'rywffor': [{'ORTH': 'rywffor', 'LEMMA': 'rhywffordd', 'NORM': 'rywffordd'}],
    "rywffor'": [{'ORTH': "rywffor'", 'LEMMA': 'rhywffordd', 'NORM': 'rywffordd'}],
    "rh'wla": [{'ORTH': "rh'wla", 'LEMMA': 'rhywle', 'NORM': 'rhywle'}],
    'rwla': [{'ORTH': 'rwla', 'LEMMA': 'rhywle', 'NORM': 'rhywle'}],
    "r'wle": [{'ORTH': "r'wle", 'LEMMA': 'rhywle', 'NORM': 'rywle'}],
    'rwle': [{'ORTH': 'rwle', 'LEMMA': 'rhywle', 'NORM': 'rywle'}],
    'rywla': [{'ORTH': 'rywla', 'LEMMA': 'rhywle', 'NORM': 'rywle'}],
    "r'ywun": [{'ORTH': "r'ywun", 'LEMMA': 'rhywun', 'NORM': 'rhywun'}],
    'rhiwyn': [{'ORTH': 'rhiwyn', 'LEMMA': 'rhywun', 'NORM': 'rhywun'}],
    "r'wun": [{'ORTH': "r'wun", 'LEMMA': 'rhywun', 'NORM': 'rywun'}],
    'onin': [{'ORTH': 'onin', 'LEMMA': 'roeddwn i yn', 'NORM': 'roeddwn i yn'}],
    "'wy'n": [{'ORTH': "'wy'n", 'LEMMA': "rwy'n", 'NORM': "rwy'n"}],
    "'wi": [{'ORTH': "'wi", 'LEMMA': 'rydw i', 'NORM': 'rydw i'}],
    'wi': [{'ORTH': 'wi', 'LEMMA': 'rydw i', 'NORM': 'rydw i'}],
    'dwin': [{'ORTH': 'dwin', 'LEMMA': 'rydw i yn', 'NORM': 'rydw i yn'}],
    'ŵan': [{'ORTH': 'ŵan', 'LEMMA': 'rŵan', 'NORM': 'rŵan'}],
    'safone': [{'ORTH': 'safone', 'LEMMA': 'safon', 'NORM': 'safonau'}],
    'saithdege': [{'ORTH': 'saithdege', 'LEMMA': 'saithdegau', 'NORM': 'saithdegau'}],
    'sesiynne': [{'ORTH': 'sesiynne', 'LEMMA': 'sesiwn', 'NORM': 'sesiynnau'}],
    'sgilia': [{'ORTH': 'sgilia', 'LEMMA': 'sgil', 'NORM': 'sgiliau'}],
    'sgilie': [{'ORTH': 'sgilie', 'LEMMA': 'sgil', 'NORM': 'sgiliau'}],
    'siwd': [{'ORTH': 'siwd', 'LEMMA': 'shwt', 'NORM': 'shwt'}],
    'siope': [{'ORTH': 'siope', 'LEMMA': 'siop', 'NORM': 'siopau'}],
    'shwr': [{'ORTH': 'shwr', 'LEMMA': 'siwr', 'NORM': 'siwr'}],
    'stopo': [{'ORTH': 'stopo', 'LEMMA': 'stopio', 'NORM': 'stopio'}],
    'shwd': [{'ORTH': 'shwd', 'LEMMA': 'sut', 'NORM': 'sut'}],
    'sud': [{'ORTH': 'sud', 'LEMMA': 'sut', 'NORM': 'sut'}],
    'swpar': [{'ORTH': 'swpar', 'LEMMA': 'swper', 'NORM': 'swper'}],
    'sylwade': [{'ORTH': 'sylwade', 'LEMMA': 'sylw', 'NORM': 'sylwadau'}],
    'syniada': [{'ORTH': 'syniada', 'LEMMA': 'syniad', 'NORM': 'syniadau'}],
    'syniade': [{'ORTH': 'syniade', 'LEMMA': 'syniad', 'NORM': 'syniadau'}],
    'damed': [{'ORTH': 'damed', 'LEMMA': 'tamaid', 'NORM': 'damaid'}],
    'tamed': [{'ORTH': 'tamed', 'LEMMA': 'tamaid', 'NORM': 'tamaid'}],
    "t'imlo": [{'ORTH': "t'imlo", 'LEMMA': 'teimlo', 'NORM': 'teimlo'}],
    'timlo': [{'ORTH': 'timlo', 'LEMMA': 'teimlo', 'NORM': 'teimlo'}],
    "ti'sho": [{'ORTH': "ti'sho", 'LEMMA': 'ti eisiau', 'NORM': 'ti eisiau'}],
    'tisho': [{'ORTH': 'tisho', 'LEMMA': 'ti eisiau', 'NORM': 'ti eisiau'}],
    'chdin': [{'ORTH': 'chdin', 'LEMMA': 'ti yn', 'NORM': 'ti yn'}],
    "t'wel": [{'ORTH': "t'wel", 'LEMMA': "ti'n gweld", 'NORM': "ti'n gweld"}],
    "t'bo": [{'ORTH': "t'bo", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "t'bod": [{'ORTH': "t'bod", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "t'io": [{'ORTH': "t'io", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "t'mo": [{'ORTH': "t'mo", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "t'mod": [{'ORTH': "t'mod", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "t'od": [{'ORTH': "t'od", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "ti'mo": [{'ORTH': "ti'mo", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "ti'mod": [{'ORTH': "ti'mod", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "ti'o": [{'ORTH': "ti'o", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    "ti'od": [{'ORTH': "ti'od", 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    'timod': [{'ORTH': 'timod', 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    'tmod': [{'ORTH': 'tmod', 'LEMMA': "ti'n gwybod", 'NORM': "ti'n gwybod"}],
    'pyn': [{'ORTH': 'pyn', 'LEMMA': 'tipyn', 'NORM': 'tipyn'}],
    'traethode': [{'ORTH': 'traethode', 'LEMMA': 'traethawd', 'NORM': 'traethodau'}],
    'trafeilio': [{'ORTH': 'trafeilio', 'LEMMA': 'trafaelio', 'NORM': 'trafaelio'}],
    'dre': [{'ORTH': 'dre', 'LEMMA': 'tref', 'NORM': 'dref'}],
    "dre'": [{'ORTH': "dre'", 'LEMMA': 'tref', 'NORM': 'dref'}],
    'tre': [{'ORTH': 'tre', 'LEMMA': 'tref', 'NORM': 'tref'}],
    "tre'": [{'ORTH': "tre'", 'LEMMA': 'tref', 'NORM': 'tref'}],
    'drw': [{'ORTH': 'drw', 'LEMMA': 'trwy', 'NORM': 'drwy'}],
    "drw'": [{'ORTH': "drw'", 'LEMMA': 'trwy', 'NORM': 'drwy'}],
    'drwadd': [{'ORTH': 'drwadd', 'LEMMA': 'trwy', 'NORM': 'drwyodd'}],
    'trw': [{'ORTH': 'trw', 'LEMMA': 'trwy', 'NORM': 'trwy'}],
    "trw'": [{'ORTH': "trw'", 'LEMMA': 'trwy', 'NORM': 'trwy'}],
    "'ua": [{'ORTH': "'ua", 'LEMMA': 'tua', 'NORM': 'tua'}],
    'dullie': [{'ORTH': 'dullie', 'LEMMA': 'tull', 'NORM': 'dulliau'}],
    'ucha': [{'ORTH': 'ucha', 'LEMMA': 'uchaf', 'NORM': 'uchaf'}],
    'uchal': [{'ORTH': 'uchal', 'LEMMA': 'uchel', 'NORM': 'uchel'}],
    'ugen': [{'ORTH': 'ugen', 'LEMMA': 'ugain', 'NORM': 'ugain'}],
    'ugian': [{'ORTH': 'ugian', 'LEMMA': 'ugain', 'NORM': 'ugain'}],
    'unarddeg': [{'ORTH': 'unarddeg', 'LEMMA': 'un ar ddeg', 'NORM': 'un ar ddeg'}],
    'undeg': [{'ORTH': 'undeg', 'LEMMA': 'un deg', 'NORM': 'un deg'}],
    'unrhywbeth': [{'ORTH': 'unrhywbeth', 'LEMMA': 'unrhyw beth', 'NORM': 'unrhyw beth'}],
    'unrhywun': [{'ORTH': 'unrhywun', 'LEMMA': 'unrhyw un', 'NORM': 'unrhyw un'}],
    'unweth': [{'ORTH': 'unweth', 'LEMMA': 'unwaith', 'NORM': 'unwaith'}],
    'weithe': [{'ORTH': 'weithe', 'LEMMA': 'waith', 'NORM': 'weithiau'}],
    'wedyni': [{'ORTH': 'wedyni', 'LEMMA': 'wedi hynny', 'NORM': 'wedi hynny'}],
    'weithie': [{'ORTH': 'weithie', 'LEMMA': 'weithiau', 'NORM': 'weithiau'}],
    "'tho": [{'ORTH': "'tho", 'LEMMA': 'wrth', 'NORM': 'wrtho'}],
    'tho': [{'ORTH': 'tho', 'LEMMA': 'wrth', 'NORM': 'wrtho'}],
    "'thoch": [{'ORTH': "'thoch", 'LEMMA': 'wrth', 'NORM': 'wrthoch'}],
    'thoch': [{'ORTH': 'thoch', 'LEMMA': 'wrth', 'NORM': 'wrthoch'}],
    'wrthach': [{'ORTH': 'wrthach', 'LEMMA': 'wrth', 'NORM': 'wrthych'}],
    'wrthai': [{'ORTH': 'wrthai', 'LEMMA': 'wrth', 'NORM': 'wrthyf i'}],
    "'than": [{'ORTH': "'than", 'LEMMA': 'wrth', 'NORM': 'wrthyn'}],
    'wrthat': [{'ORTH': 'wrthat', 'LEMMA': 'wrth', 'NORM': 'wrthyt'}],
    "wybod'eth": [{'ORTH': "wybod'eth", 'LEMMA': 'wybodaeth', 'NORM': 'wybodaeth'}],
    'wybodeth': [{'ORTH': 'wybodeth', 'LEMMA': 'wybodaeth', 'NORM': 'wybodaeth'}],
    'sti': [{'ORTH': 'sti', 'LEMMA': 'wyddost ti', 'NORM': 'wyddost ti'}],
    'gwynab': [{'ORTH': 'gwynab', 'LEMMA': 'wyneb', 'NORM': 'wyneb'}],
    'gwyneb': [{'ORTH': 'gwyneb', 'LEMMA': 'wyneb', 'NORM': 'wyneb'}],
    'wynab': [{'ORTH': 'wynab', 'LEMMA': 'wyneb', 'NORM': 'wyneb'}],
    "w'snos": [{'ORTH': "w'snos", 'LEMMA': 'wythnos', 'NORM': 'wythnos'}],
    "w'sos": [{'ORTH': "w'sos", 'LEMMA': 'wythnos', 'NORM': 'wythnos'}],
    "w'thnos": [{'ORTH': "w'thnos", 'LEMMA': 'wythnos', 'NORM': 'wythnos'}],
    'wsnos': [{'ORTH': 'wsnos', 'LEMMA': 'wythnos', 'NORM': 'wythnos'}],
    'wsos': [{'ORTH': 'wsos', 'LEMMA': 'wythnos', 'NORM': 'wythnos'}],
    'wthnos': [{'ORTH': 'wthnos', 'LEMMA': 'wythnos', 'NORM': 'wythnos'}],
    'wythnosa': [{'ORTH': 'wythnosa', 'LEMMA': 'wythnos', 'NORM': 'wythnosau'}],
    'wythnose': [{'ORTH': 'wythnose', 'LEMMA': 'wythnos', 'NORM': 'wythnosau'}],
    "'chydig": [{'ORTH': "'chydig", 'LEMMA': 'ychydig', 'NORM': 'ychydig'}],
    'chdig': [{'ORTH': 'chdig', 'LEMMA': 'ychydig', 'NORM': 'ychydig'}],
    'chydig': [{'ORTH': 'chydig', 'LEMMA': 'ychydig', 'NORM': 'ychydig'}],
    'ydio': [{'ORTH': 'ydio', 'LEMMA': 'ydi o', 'NORM': 'ydi o'}],
    'yfad': [{'ORTH': 'yfad', 'LEMMA': 'yfed', 'NORM': 'yfed'}],
    "'fory": [{'ORTH': "'fory", 'LEMMA': 'yfory', 'NORM': 'yfory'}],
    'fory': [{'ORTH': 'fory', 'LEMMA': 'yfory', 'NORM': 'yfory'}],
    'mestyn': [{'ORTH': 'mestyn', 'LEMMA': 'ymestyn', 'NORM': 'ymestyn'}],
    "'la'n": [{'ORTH': "'la'n", 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    "'laen": [{'ORTH': "'laen", 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    "'mla'n": [{'ORTH': "'mla'n", 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    "'mlaen": [{'ORTH': "'mlaen", 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    'laen': [{'ORTH': 'laen', 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    'mlaen': [{'ORTH': 'mlaen', 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    'mlan': [{'ORTH': 'mlan', 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    'mlân': [{'ORTH': 'mlân', 'LEMMA': 'ymlaen', 'NORM': 'ymlaen'}],
    'molchi': [{'ORTH': 'molchi', 'LEMMA': 'ymolchi', 'NORM': 'ymolchi'}],
    'yml': [{'ORTH': 'yml', 'LEMMA': 'ymyl', 'NORM': 'ymyl'}],
    "yn'o": [{'ORTH': "yn'o", 'LEMMA': 'yn', 'NORM': 'ynddo'}],
    'noch': [{'ORTH': 'noch', 'LEMMA': 'yn', 'NORM': 'ynoch'}],
    "'nof": [{'ORTH': "'nof", 'LEMMA': 'yn', 'NORM': 'ynof'}],
    "'nawr": [{'ORTH': "'nawr", 'LEMMA': 'yn awr', 'NORM': 'yn awr'}],
    'nawr': [{'ORTH': 'nawr', 'LEMMA': 'yn awr', 'NORM': 'yn awr'}],
    "'nôl": [{'ORTH': "'nôl", 'LEMMA': 'yn ôl', 'NORM': 'yn ôl'}],
    "n'ol": [{'ORTH': "n'ol", 'LEMMA': 'yn ôl', 'NORM': 'yn ôl'}],
    'nôl': [{'ORTH': 'nôl', 'LEMMA': 'yn ôl', 'NORM': 'yn ôl'}],
    "'a": [{'ORTH': "'a", 'LEMMA': 'yna', 'NORM': 'yna'}],
    'yne': [{'ORTH': 'yne', 'LEMMA': 'yna', 'NORM': 'yna'}],
    'yndda': [{'ORTH': 'yndda', 'LEMMA': 'ynddo', 'NORM': 'ynddo'}],
    'nno': [{'ORTH': 'nno', 'LEMMA': 'ynno', 'NORM': 'ynno'}],
    "'nno": [{'ORTH': "'nno", 'LEMMA': 'yno', 'NORM': 'yno'}],
    "'ta": [{'ORTH': "'ta", 'LEMMA': 'yntau', 'NORM': 'yntau'}],
    'ta': [{'ORTH': 'ta', 'LEMMA': 'yntau', 'NORM': 'yntau'}],
    'rhen': [{'ORTH': 'rhen', 'LEMMA': 'yr hen', 'NORM': 'yr hen'}],
    "r'un": [{'ORTH': "r'un", 'LEMMA': 'yr un', 'NORM': 'yr un'}],
    "'rysgol": [{'ORTH': "'rysgol", 'LEMMA': 'yr ysgol', 'NORM': 'yr ysgol'}],
    'rysgol': [{'ORTH': 'rysgol', 'LEMMA': 'yr ysgol', 'NORM': 'yr ysgol'}],
    'sgwn': [{'ORTH': 'sgwn', 'LEMMA': 'ys gwn', 'NORM': 'ys gwn'}],
    'sbyty': [{'ORTH': 'sbyty', 'LEMMA': 'ysbyty', 'NORM': 'ysbyty'}],
    'sgrifen': [{'ORTH': 'sgrifen', 'LEMMA': 'ysgrifen', 'NORM': 'ysgrifen'}],
    "'sgrifennu": [{'ORTH': "'sgrifennu", 'LEMMA': 'ysgrifennu', 'NORM': 'ysgrifennu'}],
    'sgrifennu': [{'ORTH': 'sgrifennu', 'LEMMA': 'ysgrifennu', 'NORM': 'ysgrifennu'}],
    "'sgubo": [{'ORTH': "'sgubo", 'LEMMA': 'ysgubo', 'NORM': 'ysgubo'}],
    'sgubo': [{'ORTH': 'sgubo', 'LEMMA': 'ysgubo', 'NORM': 'ysgubo'}],
    "'sgwydda": [{'ORTH': "'sgwydda", 'LEMMA': 'ysgwyddau', 'NORM': 'ysgwyddau'}],
    "'sgwyddau": [{'ORTH': "'sgwyddau", 'LEMMA': 'ysgwyddau', 'NORM': 'ysgwyddau'}],
    "'sgwydde": [{'ORTH': "'sgwydde", 'LEMMA': 'ysgwyddau', 'NORM': 'ysgwyddau'}],
    'sgwydda': [{'ORTH': 'sgwydda', 'LEMMA': 'ysgwyddau', 'NORM': 'ysgwyddau'}],
    'sgwyddau': [{'ORTH': 'sgwyddau', 'LEMMA': 'ysgwyddau', 'NORM': 'ysgwyddau'}],
    'sgwydde': [{'ORTH': 'sgwydde', 'LEMMA': 'ysgwyddau', 'NORM': 'ysgwyddau'}],
    "'stafell": [{'ORTH': "'stafell", 'LEMMA': 'ystafell', 'NORM': 'ystafell'}],
    'stafall': [{'ORTH': 'stafall', 'LEMMA': 'ystafell', 'NORM': 'ystafell'}],
    'stafell': [{'ORTH': 'stafell', 'LEMMA': 'ystafell', 'NORM': 'ystafell'}],
    'stafelloedd': [{'ORTH': 'stafelloedd', 'LEMMA': 'ystafell', 'NORM': 'ystafelloedd'}],
    'styfnig': [{'ORTH': 'styfnig', 'LEMMA': 'ystyfnig', 'NORM': 'ystyfnig'}]}



# Times

for h in range(1, 12 + 1):
    for period in ["a.m.", "am"]:
        TOKENIZER_EXCEPTIONS["%d%s" % (h, period)] = [
            {ORTH: "%d" % h},
            {ORTH: period, LEMMA: "a.m.", NORM: "a.m."},
        ]
    for period in ["p.m.", "pm"]:
        TOKENIZER_EXCEPTIONS["%d%s" % (h, period)] = [
            {ORTH: "%d" % h},
            {ORTH: period, LEMMA: "p.m.", NORM: "p.m."},
        ]

for orth in [
    "'d",
    "a.m.",
    "Adm.",
    "Bros.",
    "co.",
    "Co.",
    "Corp.",
    "D.C.",
    "Dr.",
    "e.g.",
    "E.g.",
    "E.G.",
    "Gen.",
    "Gov.",
    "i.e.",
    "I.e.",
    "I.E.",
    "Inc.",
    "Jr.",
    "Ltd.",
    "Md.",
    "Messrs.",
    "Mo.",
    "Mont.",
    "Mr.",
    "Mrs.",
    "Ms.",
    "p.m.",
    "Ph.D.",
    "Prof.",
    "Rep.",
    "Rev.",
    "Sen.",
    "St.",
    "vs.",
    "v.s.",
]:
    TOKENIZER_EXCEPTIONS[orth] = [{ORTH: orth}]
